package sigefirrhh.persistencia.modelo;

import java.util.Date;

public class RegularizacionCompromiso {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column regularizacioncompromiso.id_compromiso_inicial
     *
     * @ibatorgenerated Fri May 29 15:27:21 VET 2015
     */
    private Integer idCompromisoInicial;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column regularizacioncompromiso.id_regularizacion_compromiso_inicial
     *
     * @ibatorgenerated Fri May 29 15:27:21 VET 2015
     */
    private Integer idRegularizacionCompromisoInicial;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column regularizacioncompromiso.expediente
     *
     * @ibatorgenerated Fri May 29 15:27:21 VET 2015
     */
    private Long expediente;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column regularizacioncompromiso.compromiso
     *
     * @ibatorgenerated Fri May 29 15:27:21 VET 2015
     */
    private Long compromiso;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column regularizacioncompromiso.ano
     *
     * @ibatorgenerated Fri May 29 15:27:21 VET 2015
     */
    private Integer ano;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column regularizacioncompromiso.tarea
     *
     * @ibatorgenerated Fri May 29 15:27:21 VET 2015
     */
    private Integer tarea;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column regularizacioncompromiso.estatus
     *
     * @ibatorgenerated Fri May 29 15:27:21 VET 2015
     */
    private Integer estatus;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column regularizacioncompromiso.id_tipo_documento
     *
     * @ibatorgenerated Fri May 29 15:27:21 VET 2015
     */
    private Integer idTipoDocumento;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column regularizacioncompromiso.documento
     *
     * @ibatorgenerated Fri May 29 15:27:21 VET 2015
     */
    private String documento;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column regularizacioncompromiso.observacion
     *
     * @ibatorgenerated Fri May 29 15:27:21 VET 2015
     */
    private String observacion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column regularizacioncompromiso.gaceta_cred_adicional
     *
     * @ibatorgenerated Fri May 29 15:27:21 VET 2015
     */
    private String gacetaCredAdicional;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column regularizacioncompromiso.decreto_cred_adicional
     *
     * @ibatorgenerated Fri May 29 15:27:21 VET 2015
     */
    private String decretoCredAdicional;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column regularizacioncompromiso.fecha_cred_adicional
     *
     * @ibatorgenerated Fri May 29 15:27:21 VET 2015
     */
    private Date fechaCredAdicional;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column regularizacioncompromiso.gaceta_rectificacion
     *
     * @ibatorgenerated Fri May 29 15:27:21 VET 2015
     */
    private String gacetaRectificacion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column regularizacioncompromiso.decreto_rectificacion
     *
     * @ibatorgenerated Fri May 29 15:27:21 VET 2015
     */
    private String decretoRectificacion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column regularizacioncompromiso.fecha_rectificacion
     *
     * @ibatorgenerated Fri May 29 15:27:21 VET 2015
     */
    private Date fechaRectificacion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column regularizacioncompromiso.fecha_registro
     *
     * @ibatorgenerated Fri May 29 15:27:21 VET 2015
     */
    private Date fechaRegistro;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column regularizacioncompromiso.origen_presupuestario
     *
     * @ibatorgenerated Fri May 29 15:27:21 VET 2015
     */
    private String origenPresupuestario;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column regularizacioncompromiso.id_compromiso_inicial
     *
     * @return the value of regularizacioncompromiso.id_compromiso_inicial
     *
     * @ibatorgenerated Fri May 29 15:27:21 VET 2015
     */
    public Integer getIdCompromisoInicial() {
        return idCompromisoInicial;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column regularizacioncompromiso.id_compromiso_inicial
     *
     * @param idCompromisoInicial the value for regularizacioncompromiso.id_compromiso_inicial
     *
     * @ibatorgenerated Fri May 29 15:27:21 VET 2015
     */
    public void setIdCompromisoInicial(Integer idCompromisoInicial) {
        this.idCompromisoInicial = idCompromisoInicial;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column regularizacioncompromiso.id_regularizacion_compromiso_inicial
     *
     * @return the value of regularizacioncompromiso.id_regularizacion_compromiso_inicial
     *
     * @ibatorgenerated Fri May 29 15:27:21 VET 2015
     */
    public Integer getIdRegularizacionCompromisoInicial() {
        return idRegularizacionCompromisoInicial;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column regularizacioncompromiso.id_regularizacion_compromiso_inicial
     *
     * @param idRegularizacionCompromisoInicial the value for regularizacioncompromiso.id_regularizacion_compromiso_inicial
     *
     * @ibatorgenerated Fri May 29 15:27:21 VET 2015
     */
    public void setIdRegularizacionCompromisoInicial(Integer idRegularizacionCompromisoInicial) {
        this.idRegularizacionCompromisoInicial = idRegularizacionCompromisoInicial;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column regularizacioncompromiso.expediente
     *
     * @return the value of regularizacioncompromiso.expediente
     *
     * @ibatorgenerated Fri May 29 15:27:21 VET 2015
     */
    public Long getExpediente() {
        return expediente;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column regularizacioncompromiso.expediente
     *
     * @param expediente the value for regularizacioncompromiso.expediente
     *
     * @ibatorgenerated Fri May 29 15:27:21 VET 2015
     */
    public void setExpediente(Long expediente) {
        this.expediente = expediente;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column regularizacioncompromiso.compromiso
     *
     * @return the value of regularizacioncompromiso.compromiso
     *
     * @ibatorgenerated Fri May 29 15:27:21 VET 2015
     */
    public Long getCompromiso() {
        return compromiso;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column regularizacioncompromiso.compromiso
     *
     * @param compromiso the value for regularizacioncompromiso.compromiso
     *
     * @ibatorgenerated Fri May 29 15:27:21 VET 2015
     */
    public void setCompromiso(Long compromiso) {
        this.compromiso = compromiso;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column regularizacioncompromiso.ano
     *
     * @return the value of regularizacioncompromiso.ano
     *
     * @ibatorgenerated Fri May 29 15:27:21 VET 2015
     */
    public Integer getAno() {
        return ano;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column regularizacioncompromiso.ano
     *
     * @param ano the value for regularizacioncompromiso.ano
     *
     * @ibatorgenerated Fri May 29 15:27:21 VET 2015
     */
    public void setAno(Integer ano) {
        this.ano = ano;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column regularizacioncompromiso.tarea
     *
     * @return the value of regularizacioncompromiso.tarea
     *
     * @ibatorgenerated Fri May 29 15:27:21 VET 2015
     */
    public Integer getTarea() {
        return tarea;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column regularizacioncompromiso.tarea
     *
     * @param tarea the value for regularizacioncompromiso.tarea
     *
     * @ibatorgenerated Fri May 29 15:27:21 VET 2015
     */
    public void setTarea(Integer tarea) {
        this.tarea = tarea;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column regularizacioncompromiso.estatus
     *
     * @return the value of regularizacioncompromiso.estatus
     *
     * @ibatorgenerated Fri May 29 15:27:21 VET 2015
     */
    public Integer getEstatus() {
        return estatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column regularizacioncompromiso.estatus
     *
     * @param estatus the value for regularizacioncompromiso.estatus
     *
     * @ibatorgenerated Fri May 29 15:27:21 VET 2015
     */
    public void setEstatus(Integer estatus) {
        this.estatus = estatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column regularizacioncompromiso.id_tipo_documento
     *
     * @return the value of regularizacioncompromiso.id_tipo_documento
     *
     * @ibatorgenerated Fri May 29 15:27:21 VET 2015
     */
    public Integer getIdTipoDocumento() {
        return idTipoDocumento;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column regularizacioncompromiso.id_tipo_documento
     *
     * @param idTipoDocumento the value for regularizacioncompromiso.id_tipo_documento
     *
     * @ibatorgenerated Fri May 29 15:27:21 VET 2015
     */
    public void setIdTipoDocumento(Integer idTipoDocumento) {
        this.idTipoDocumento = idTipoDocumento;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column regularizacioncompromiso.documento
     *
     * @return the value of regularizacioncompromiso.documento
     *
     * @ibatorgenerated Fri May 29 15:27:21 VET 2015
     */
    public String getDocumento() {
        return documento;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column regularizacioncompromiso.documento
     *
     * @param documento the value for regularizacioncompromiso.documento
     *
     * @ibatorgenerated Fri May 29 15:27:21 VET 2015
     */
    public void setDocumento(String documento) {
        this.documento = documento == null ? null : documento.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column regularizacioncompromiso.observacion
     *
     * @return the value of regularizacioncompromiso.observacion
     *
     * @ibatorgenerated Fri May 29 15:27:21 VET 2015
     */
    public String getObservacion() {
        return observacion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column regularizacioncompromiso.observacion
     *
     * @param observacion the value for regularizacioncompromiso.observacion
     *
     * @ibatorgenerated Fri May 29 15:27:21 VET 2015
     */
    public void setObservacion(String observacion) {
        this.observacion = observacion == null ? null : observacion.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column regularizacioncompromiso.gaceta_cred_adicional
     *
     * @return the value of regularizacioncompromiso.gaceta_cred_adicional
     *
     * @ibatorgenerated Fri May 29 15:27:21 VET 2015
     */
    public String getGacetaCredAdicional() {
        return gacetaCredAdicional;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column regularizacioncompromiso.gaceta_cred_adicional
     *
     * @param gacetaCredAdicional the value for regularizacioncompromiso.gaceta_cred_adicional
     *
     * @ibatorgenerated Fri May 29 15:27:21 VET 2015
     */
    public void setGacetaCredAdicional(String gacetaCredAdicional) {
        this.gacetaCredAdicional = gacetaCredAdicional == null ? null : gacetaCredAdicional.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column regularizacioncompromiso.decreto_cred_adicional
     *
     * @return the value of regularizacioncompromiso.decreto_cred_adicional
     *
     * @ibatorgenerated Fri May 29 15:27:21 VET 2015
     */
    public String getDecretoCredAdicional() {
        return decretoCredAdicional;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column regularizacioncompromiso.decreto_cred_adicional
     *
     * @param decretoCredAdicional the value for regularizacioncompromiso.decreto_cred_adicional
     *
     * @ibatorgenerated Fri May 29 15:27:21 VET 2015
     */
    public void setDecretoCredAdicional(String decretoCredAdicional) {
        this.decretoCredAdicional = decretoCredAdicional == null ? null : decretoCredAdicional.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column regularizacioncompromiso.fecha_cred_adicional
     *
     * @return the value of regularizacioncompromiso.fecha_cred_adicional
     *
     * @ibatorgenerated Fri May 29 15:27:21 VET 2015
     */
    public Date getFechaCredAdicional() {
        return fechaCredAdicional;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column regularizacioncompromiso.fecha_cred_adicional
     *
     * @param fechaCredAdicional the value for regularizacioncompromiso.fecha_cred_adicional
     *
     * @ibatorgenerated Fri May 29 15:27:21 VET 2015
     */
    public void setFechaCredAdicional(Date fechaCredAdicional) {
        this.fechaCredAdicional = fechaCredAdicional;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column regularizacioncompromiso.gaceta_rectificacion
     *
     * @return the value of regularizacioncompromiso.gaceta_rectificacion
     *
     * @ibatorgenerated Fri May 29 15:27:21 VET 2015
     */
    public String getGacetaRectificacion() {
        return gacetaRectificacion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column regularizacioncompromiso.gaceta_rectificacion
     *
     * @param gacetaRectificacion the value for regularizacioncompromiso.gaceta_rectificacion
     *
     * @ibatorgenerated Fri May 29 15:27:21 VET 2015
     */
    public void setGacetaRectificacion(String gacetaRectificacion) {
        this.gacetaRectificacion = gacetaRectificacion == null ? null : gacetaRectificacion.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column regularizacioncompromiso.decreto_rectificacion
     *
     * @return the value of regularizacioncompromiso.decreto_rectificacion
     *
     * @ibatorgenerated Fri May 29 15:27:21 VET 2015
     */
    public String getDecretoRectificacion() {
        return decretoRectificacion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column regularizacioncompromiso.decreto_rectificacion
     *
     * @param decretoRectificacion the value for regularizacioncompromiso.decreto_rectificacion
     *
     * @ibatorgenerated Fri May 29 15:27:21 VET 2015
     */
    public void setDecretoRectificacion(String decretoRectificacion) {
        this.decretoRectificacion = decretoRectificacion == null ? null : decretoRectificacion.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column regularizacioncompromiso.fecha_rectificacion
     *
     * @return the value of regularizacioncompromiso.fecha_rectificacion
     *
     * @ibatorgenerated Fri May 29 15:27:21 VET 2015
     */
    public Date getFechaRectificacion() {
        return fechaRectificacion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column regularizacioncompromiso.fecha_rectificacion
     *
     * @param fechaRectificacion the value for regularizacioncompromiso.fecha_rectificacion
     *
     * @ibatorgenerated Fri May 29 15:27:21 VET 2015
     */
    public void setFechaRectificacion(Date fechaRectificacion) {
        this.fechaRectificacion = fechaRectificacion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column regularizacioncompromiso.fecha_registro
     *
     * @return the value of regularizacioncompromiso.fecha_registro
     *
     * @ibatorgenerated Fri May 29 15:27:21 VET 2015
     */
    public Date getFechaRegistro() {
        return fechaRegistro;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column regularizacioncompromiso.fecha_registro
     *
     * @param fechaRegistro the value for regularizacioncompromiso.fecha_registro
     *
     * @ibatorgenerated Fri May 29 15:27:21 VET 2015
     */
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column regularizacioncompromiso.origen_presupuestario
     *
     * @return the value of regularizacioncompromiso.origen_presupuestario
     *
     * @ibatorgenerated Fri May 29 15:27:21 VET 2015
     */
    public String getOrigenPresupuestario() {
        return origenPresupuestario;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column regularizacioncompromiso.origen_presupuestario
     *
     * @param origenPresupuestario the value for regularizacioncompromiso.origen_presupuestario
     *
     * @ibatorgenerated Fri May 29 15:27:21 VET 2015
     */
    public void setOrigenPresupuestario(String origenPresupuestario) {
        this.origenPresupuestario = origenPresupuestario == null ? null : origenPresupuestario.trim();
    }
}