package sigefirrhh.persistencia.modelo;

public class UnidadAdministradora {
    
    private Integer idUnidadAdministradora;
    private Integer ano;
    private Integer idOrganismo;
    private Integer codUnidadAdministradora;
    private String denominacion;
    private String codPagadora;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column unidad_administradora.vigente
     *
     * @ibatorgenerated Fri Nov 14 00:19:43 VET 2014
     */
    private String vigente;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column unidad_administradora.id_unidad_administradora
     *
     * @return the value of unidad_administradora.id_unidad_administradora
     *
     * @ibatorgenerated Fri Nov 14 00:19:43 VET 2014
     */
    public Integer getIdUnidadAdministradora() {
        return idUnidadAdministradora;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column unidad_administradora.id_unidad_administradora
     *
     * @param idUnidadAdministradora the value for unidad_administradora.id_unidad_administradora
     *
     * @ibatorgenerated Fri Nov 14 00:19:43 VET 2014
     */
    public void setIdUnidadAdministradora(Integer idUnidadAdministradora) {
        this.idUnidadAdministradora = idUnidadAdministradora;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column unidad_administradora.ano
     *
     * @return the value of unidad_administradora.ano
     *
     * @ibatorgenerated Fri Nov 14 00:19:43 VET 2014
     */
    public Integer getAno() {
        return ano;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column unidad_administradora.ano
     *
     * @param ano the value for unidad_administradora.ano
     *
     * @ibatorgenerated Fri Nov 14 00:19:43 VET 2014
     */
    public void setAno(Integer ano) {
        this.ano = ano;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column unidad_administradora.id_organismo
     *
     * @return the value of unidad_administradora.id_organismo
     *
     * @ibatorgenerated Fri Nov 14 00:19:43 VET 2014
     */
    public Integer getIdOrganismo() {
        return idOrganismo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column unidad_administradora.id_organismo
     *
     * @param idOrganismo the value for unidad_administradora.id_organismo
     *
     * @ibatorgenerated Fri Nov 14 00:19:43 VET 2014
     */
    public void setIdOrganismo(Integer idOrganismo) {
        this.idOrganismo = idOrganismo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column unidad_administradora.cod_unidad_administradora
     *
     * @return the value of unidad_administradora.cod_unidad_administradora
     *
     * @ibatorgenerated Fri Nov 14 00:19:43 VET 2014
     */
    public Integer getCodUnidadAdministradora() {
        return codUnidadAdministradora;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column unidad_administradora.cod_unidad_administradora
     *
     * @param codUnidadAdministradora the value for unidad_administradora.cod_unidad_administradora
     *
     * @ibatorgenerated Fri Nov 14 00:19:43 VET 2014
     */
    public void setCodUnidadAdministradora(Integer codUnidadAdministradora) {
        this.codUnidadAdministradora = codUnidadAdministradora;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column unidad_administradora.denominacion
     *
     * @return the value of unidad_administradora.denominacion
     *
     * @ibatorgenerated Fri Nov 14 00:19:43 VET 2014
     */
    public String getDenominacion() {
        return denominacion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column unidad_administradora.denominacion
     *
     * @param denominacion the value for unidad_administradora.denominacion
     *
     * @ibatorgenerated Fri Nov 14 00:19:43 VET 2014
     */
    public void setDenominacion(String denominacion) {
        this.denominacion = denominacion == null ? null : denominacion.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column unidad_administradora.cod_pagadora
     *
     * @return the value of unidad_administradora.cod_pagadora
     *
     * @ibatorgenerated Fri Nov 14 00:19:43 VET 2014
     */
    public String getCodPagadora() {
        return codPagadora;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column unidad_administradora.cod_pagadora
     *
     * @param codPagadora the value for unidad_administradora.cod_pagadora
     *
     * @ibatorgenerated Fri Nov 14 00:19:43 VET 2014
     */
    public void setCodPagadora(String codPagadora) {
        this.codPagadora = codPagadora == null ? null : codPagadora.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column unidad_administradora.vigente
     *
     * @return the value of unidad_administradora.vigente
     *
     * @ibatorgenerated Fri Nov 14 00:19:43 VET 2014
     */
    public String getVigente() {
        return vigente;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column unidad_administradora.vigente
     *
     * @param vigente the value for unidad_administradora.vigente
     *
     * @ibatorgenerated Fri Nov 14 00:19:43 VET 2014
     */
    public void setVigente(String vigente) {
        this.vigente = vigente == null ? null : vigente.trim();
    }
}