package sigefirrhh.struts.actionForm;

import org.apache.struts.action.ActionForm;

public class GastoProyectadoForm extends ActionForm{

	private static final long serialVersionUID = -2172912808130499265L;
	private String cedula;
    private String codConcepto;    
    private String descripcion;    
    private Integer idTipoPersonal;    
    private String codFrecuenciaPago;
    private Integer partida;
    private String descripPartida;
    private Integer mes;
    private Integer ano;
    private Integer idOrganismo;
    private Integer anoAs;
    private Integer codUnidadEjecutora;
    private String denoUne;

    private Integer codCatePresu;
    private String denoCp;
    private Double monto;
    
    public String getCedula() {
        return cedula;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gasto_mensual_v2.cedula
     *
     * @param cedula the value for gasto_mensual_v2.cedula
     *
     * @ibatorgenerated Wed Nov 19 08:02:23 VET 2014
     */
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
 
    public String getCodConcepto() {
        return codConcepto;
    }

    public void setCodConcepto(String codConcepto) {
        this.codConcepto = codConcepto == null ? null : codConcepto.trim();
    }

    public String getDescripcion() {
        return descripcion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gasto_mensual_v2.descripcion
     *
     * @param descripcion the value for gasto_mensual_v2.descripcion
     *
     * @ibatorgenerated Wed Nov 19 08:02:23 VET 2014
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion == null ? null : descripcion.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gasto_mensual_v2.id_tipo_personal
     *
     * @return the value of gasto_mensual_v2.id_tipo_personal
     *
     * @ibatorgenerated Wed Nov 19 08:02:23 VET 2014
     */
    public Integer getIdTipoPersonal() {
        return idTipoPersonal;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gasto_mensual_v2.id_tipo_personal
     *
     * @param idTipoPersonal the value for gasto_mensual_v2.id_tipo_personal
     *
     * @ibatorgenerated Wed Nov 19 08:02:23 VET 2014
     */
    public void setIdTipoPersonal(Integer idTipoPersonal) {
        this.idTipoPersonal = idTipoPersonal;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gasto_mensual_v2.cod_frecuencia_pago
     *
     * @return the value of gasto_mensual_v2.cod_frecuencia_pago
     *
     * @ibatorgenerated Wed Nov 19 08:02:23 VET 2014
     */
    public String getCodFrecuenciaPago() {
        return codFrecuenciaPago;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gasto_mensual_v2.cod_frecuencia_pago
     *
     * @param codFrecuenciaPago the value for gasto_mensual_v2.cod_frecuencia_pago
     *
     * @ibatorgenerated Wed Nov 19 08:02:23 VET 2014
     */
    public void setCodFrecuenciaPago(String codFrecuenciaPago) {
        this.codFrecuenciaPago = codFrecuenciaPago;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gasto_mensual_v2.partida
     *
     * @return the value of gasto_mensual_v2.partida
     *
     * @ibatorgenerated Wed Nov 19 08:02:23 VET 2014
     */
    public Integer getPartida() {
        return partida;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gasto_mensual_v2.partida
     *
     * @param partida the value for gasto_mensual_v2.partida
     *
     * @ibatorgenerated Wed Nov 19 08:02:23 VET 2014
     */
    public void setPartida(Integer partida) {
        this.partida = partida;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gasto_mensual_v2.descrip_partida
     *
     * @return the value of gasto_mensual_v2.descrip_partida
     *
     * @ibatorgenerated Wed Nov 19 08:02:23 VET 2014
     */
    public String getDescripPartida() {
        return descripPartida;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gasto_mensual_v2.descrip_partida
     *
     * @param descripPartida the value for gasto_mensual_v2.descrip_partida
     *
     * @ibatorgenerated Wed Nov 19 08:02:23 VET 2014
     */
    public void setDescripPartida(String descripPartida) {
        this.descripPartida = descripPartida == null ? null : descripPartida.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gasto_mensual_v2.mes
     *
     * @return the value of gasto_mensual_v2.mes
     *
     * @ibatorgenerated Wed Nov 19 08:02:23 VET 2014
     */
    public Integer getMes() {
        return mes;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gasto_mensual_v2.mes
     *
     * @param mes the value for gasto_mensual_v2.mes
     *
     * @ibatorgenerated Wed Nov 19 08:02:23 VET 2014
     */
    public void setMes(Integer mes) {
        this.mes = mes;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gasto_mensual_v2.ano
     *
     * @return the value of gasto_mensual_v2.ano
     *
     * @ibatorgenerated Wed Nov 19 08:02:23 VET 2014
     */
    public Integer getAno() {
        return ano;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gasto_mensual_v2.ano
     *
     * @param ano the value for gasto_mensual_v2.ano
     *
     * @ibatorgenerated Wed Nov 19 08:02:23 VET 2014
     */
    public void setAno(Integer ano) {
        this.ano = ano;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gasto_mensual_v2.id_organismo
     *
     * @return the value of gasto_mensual_v2.id_organismo
     *
     * @ibatorgenerated Wed Nov 19 08:02:23 VET 2014
     */
    public Integer getIdOrganismo() {
        return idOrganismo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gasto_mensual_v2.id_organismo
     *
     * @param idOrganismo the value for gasto_mensual_v2.id_organismo
     *
     * @ibatorgenerated Wed Nov 19 08:02:23 VET 2014
     */
    public void setIdOrganismo(Integer idOrganismo) {
        this.idOrganismo = idOrganismo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gasto_mensual_v2.ano_as
     *
     * @return the value of gasto_mensual_v2.ano_as
     *
     * @ibatorgenerated Wed Nov 19 08:02:23 VET 2014
     */
    public Integer getAnoAs() {
        return anoAs;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gasto_mensual_v2.ano_as
     *
     * @param anoAs the value for gasto_mensual_v2.ano_as
     *
     * @ibatorgenerated Wed Nov 19 08:02:23 VET 2014
     */
    public void setAnoAs(Integer anoAs) {
        this.anoAs = anoAs;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gasto_mensual_v2.cod_unidad_ejecutora
     *
     * @return the value of gasto_mensual_v2.cod_unidad_ejecutora
     *
     * @ibatorgenerated Wed Nov 19 08:02:23 VET 2014
     */
    public Integer getCodUnidadEjecutora() {
        return codUnidadEjecutora;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gasto_mensual_v2.cod_unidad_ejecutora
     *
     * @param codUnidadEjecutora the value for gasto_mensual_v2.cod_unidad_ejecutora
     *
     * @ibatorgenerated Wed Nov 19 08:02:23 VET 2014
     */
    public void setCodUnidadEjecutora(Integer codUnidadEjecutora) {
        this.codUnidadEjecutora = codUnidadEjecutora;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gasto_mensual_v2.deno_une
     *
     * @return the value of gasto_mensual_v2.deno_une
     *
     * @ibatorgenerated Wed Nov 19 08:02:23 VET 2014
     */
    public String getDenoUne() {
        return denoUne;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gasto_mensual_v2.deno_une
     *
     * @param denoUne the value for gasto_mensual_v2.deno_une
     *
     * @ibatorgenerated Wed Nov 19 08:02:23 VET 2014
     */
    public void setDenoUne(String denoUne) {
        this.denoUne = denoUne == null ? null : denoUne.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gasto_mensual_v2.cod_cate_presu
     *
     * @return the value of gasto_mensual_v2.cod_cate_presu
     *
     * @ibatorgenerated Wed Nov 19 08:02:23 VET 2014
     */
    public Integer getCodCatePresu() {
        return codCatePresu;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gasto_mensual_v2.cod_cate_presu
     *
     * @param codCatePresu the value for gasto_mensual_v2.cod_cate_presu
     *
     * @ibatorgenerated Wed Nov 19 08:02:23 VET 2014
     */
    public void setCodCatePresu(Integer codCatePresu) {
        this.codCatePresu = codCatePresu;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gasto_mensual_v2.deno_cp
     *
     * @return the value of gasto_mensual_v2.deno_cp
     *
     * @ibatorgenerated Wed Nov 19 08:02:23 VET 2014
     */
    public String getDenoCp() {
        return denoCp;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gasto_mensual_v2.deno_cp
     *
     * @param denoCp the value for gasto_mensual_v2.deno_cp
     *
     * @ibatorgenerated Wed Nov 19 08:02:23 VET 2014
     */
    public void setDenoCp(String denoCp) {
        this.denoCp = denoCp == null ? null : denoCp.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column gasto_mensual_v2.monto
     *
     * @return the value of gasto_mensual_v2.monto
     *
     * @ibatorgenerated Wed Nov 19 08:02:23 VET 2014
     */
    public Double getMonto() {
        return monto;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column gasto_mensual_v2.monto
     *
     * @param monto the value for gasto_mensual_v2.monto
     *
     * @ibatorgenerated Wed Nov 19 08:02:23 VET 2014
     */
    public void setMonto(Double monto) {
        this.monto = monto;
    }

	public void setEstatus_guardado(int i) {
		// TODO Auto-generated method stub
		
	}
}