/*<script>*/
    var libFuncName=null;if(typeof jQuery==="undefined"&&typeof Zepto==="undefined"&&typeof $==="function"){libFuncName=$;}else{if(typeof jQuery==="function"){libFuncName=jQuery;
}else{if(typeof Zepto==="function"){libFuncName=Zepto;}else{throw new TypeError();}}}(function(c,b,a,d){c("head").append('<meta class="foundation-mq-small">');
c("head").append('<meta class="foundation-mq-medium">');c("head").append('<meta class="foundation-mq-large">');b.matchMedia=b.matchMedia||(function(i,j){var g,e=i.documentElement,f=e.firstElementChild||e.firstChild,h=i.createElement("body"),k=i.createElement("div");
k.id="mq-test-1";k.style.cssText="position:absolute;top:-100em";h.style.background="none";h.appendChild(k);return function(l){k.innerHTML='&shy;<style media="'+l+'"> #mq-test-1 { width: 42px; }</style>';
e.insertBefore(h,f);g=k.offsetWidth===42;e.removeChild(h);return{matches:g,media:l};};}(a));if(!Array.prototype.filter){Array.prototype.filter=function(f){if(this==null){throw new TypeError();
}var k=Object(this),e=k.length>>>0;if(typeof f!=="function"){return;}var j=[],h=arguments[1];for(var g=0;g<e;g++){if(g in k){var l=k[g];if(f&&f.call(h,l,g,k)){j.push(l);
}}}return j;};}if(!Function.prototype.bind){Function.prototype.bind=function(e){if(typeof this!=="function"){throw new TypeError("Function.prototype.bind - what is trying to be bound is not callable");
}var i=Array.prototype.slice.call(arguments,1),h=this,f=function(){},g=function(){return h.apply(this instanceof f&&e?this:e,i.concat(Array.prototype.slice.call(arguments)));
};f.prototype=this.prototype;g.prototype=new f();return g;};}if(!Array.prototype.indexOf){Array.prototype.indexOf=function(g){if(this==null){throw new TypeError();
}var h=Object(this);var e=h.length>>>0;if(e===0){return -1;}var i=0;if(arguments.length>1){i=Number(arguments[1]);if(i!=i){i=0;}else{if(i!=0&&i!=Infinity&&i!=-Infinity){i=(i>0||-1)*Math.floor(Math.abs(i));
}}}if(i>=e){return -1;}var f=i>=0?i:Math.max(e-Math.abs(i),0);for(;f<e;f++){if(f in h&&h[f]===g){return f;}}return -1;};}c.fn.stop=c.fn.stop||function(){return this;
};b.Foundation={name:"Foundation",version:"4.3.2",cache:{},media_queries:{small:c(".foundation-mq-small").css("font-family").replace(/\'/g,""),medium:c(".foundation-mq-medium").css("font-family").replace(/\'/g,""),large:c(".foundation-mq-large").css("font-family").replace(/\'/g,"")},stylesheet:c("<style></style>").appendTo("head")[0].sheet,init:function(o,l,e,p,f,h){var j,m=[o,e,p,f],k=[],h=h||false;
if(h){this.nc=h;}this.rtl=/rtl/i.test(c("html").attr("dir"));this.scope=o||this.scope;if(l&&typeof l==="string"&&!/reflow/i.test(l)){if(/off/i.test(l)){return this.off();
}j=l.split(" ");if(j.length>0){for(var g=j.length-1;g>=0;g--){k.push(this.init_lib(j[g],m));}}}else{if(/reflow/i.test(l)){m[1]="reflow";}for(var n in this.libs){k.push(this.init_lib(n,m));
}}if(typeof l==="function"){m.unshift(l);}return this.response_obj(k,m);},response_obj:function(f,g){for(var h=0,e=g.length;h<e;h++){if(typeof g[h]==="function"){return g[h]({errors:f.filter(function(i){if(typeof i==="string"){return i;
}})});}}return f;},init_lib:function(f,e){return this.trap(function(){if(this.libs.hasOwnProperty(f)){this.patch(this.libs[f]);return this.libs[f].init.apply(this.libs[f],e);
}else{return function(){};}}.bind(this),f);},trap:function(f,h){if(!this.nc){try{return f();}catch(g){return this.error({name:h,message:"could not be initialized",more:g.name+" "+g.message});
}}return f();},patch:function(e){this.fix_outer(e);e.scope=this.scope;e.rtl=this.rtl;},inherit:function(h,f){var e=f.split(" ");for(var g=e.length-1;g>=0;
g--){if(this.lib_methods.hasOwnProperty(e[g])){this.libs[h.name][e[g]]=this.lib_methods[e[g]];}}},random_str:function(g){var f="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".split("");
if(!g){g=Math.floor(Math.random()*f.length);}var h="";for(var e=0;e<g;e++){h+=f[Math.floor(Math.random()*f.length)];}return h;},libs:{},lib_methods:{set_data:function(e,f){var g=[this.name,+new Date(),Foundation.random_str(5)].join("-");
Foundation.cache[g]=f;e.attr("data-"+this.name+"-id",g);return f;},get_data:function(e){return Foundation.cache[e.attr("data-"+this.name+"-id")];},remove_data:function(e){if(e){delete Foundation.cache[e.attr("data-"+this.name+"-id")];
e.attr("data-"+this.name+"-id","");}else{c("[data-"+this.name+"-id]").each(function(){delete Foundation.cache[c(this).attr("data-"+this.name+"-id")];c(this).attr("data-"+this.name+"-id","");
});}},throttle:function(e,f){var g=null;return function(){var i=this,h=arguments;clearTimeout(g);g=setTimeout(function(){e.apply(i,h);},f);};},data_options:function(j){var k={},i,l,h=(j.attr("data-options")||":").split(";"),g=h.length;
function f(m){return !isNaN(m-0)&&m!==null&&m!==""&&m!==false&&m!==true;}function e(m){if(typeof m==="string"){return c.trim(m);}return m;}for(i=g-1;i>=0;
i--){l=h[i].split(":");if(/true/i.test(l[1])){l[1]=true;}if(/false/i.test(l[1])){l[1]=false;}if(f(l[1])){l[1]=parseInt(l[1],10);}if(l.length===2&&l[0].length>0){k[e(l[0])]=e(l[1]);
}}return k;},delay:function(e,f){return setTimeout(e,f);},scrollTo:function(f,i,g){if(g<0){return;}var h=i-c(b).scrollTop();var e=h/g*10;this.scrollToTimerCache=setTimeout(function(){if(!isNaN(parseInt(e,10))){b.scrollTo(0,c(b).scrollTop()+e);
this.scrollTo(f,i,g-10);}}.bind(this),10);},scrollLeft:function(e){if(!e.length){return;}return("scrollLeft" in e[0])?e[0].scrollLeft:e[0].pageXOffset;
},empty:function(f){if(f.length&&f.length>0){return false;}if(f.length&&f.length===0){return true;}for(var e in f){if(hasOwnProperty.call(f,e)){return false;
}}return true;},addCustomRule:function(g,f){if(f===d){Foundation.stylesheet.insertRule(g,Foundation.stylesheet.cssRules.length);}else{var e=Foundation.media_queries[f];
if(e!==d){Foundation.stylesheet.insertRule("@media "+Foundation.media_queries[f]+"{ "+g+" }");}}}},fix_outer:function(e){e.outerHeight=function(g,f){if(typeof Zepto==="function"){return g.height();
}if(typeof f!=="undefined"){return g.outerHeight(f);}return g.outerHeight();};e.outerWidth=function(g,f){if(typeof Zepto==="function"){return g.width();
}if(typeof f!=="undefined"){return g.outerWidth(f);}return g.outerWidth();};},error:function(e){return e.name+" "+e.message+"; "+e.more;},off:function(){c(this.scope).off(".fndtn");
c(b).off(".fndtn");return true;},zj:c};c.fn.foundation=function(){var e=Array.prototype.slice.call(arguments,0);return this.each(function(){Foundation.init.apply(Foundation,[this].concat(e));
return this;});};}(libFuncName,this,this.document));(function(d,c,a,e){Foundation.libs.forms={name:"forms",version:"4.3.2",cache:{},settings:{disable_class:"no-custom",last_combo:null},init:function(g,h,f){if(typeof h==="object"){d.extend(true,this.settings,h);
}if(typeof h!=="string"){if(!this.settings.init){this.events();}this.assemble();return this.settings.init;}else{return this[h].call(this,f);}},assemble:function(){var f=this;
d('form.custom input[type="radio"],[type="checkbox"]',d(this.scope)).not('[data-customforms="disabled"]').not("."+this.settings.disable_class).each(function(g,h){f.set_custom_markup(h);
}).change(function(){f.set_custom_markup(this);});d("form.custom select",d(this.scope)).not('[data-customforms="disabled"]').not("."+this.settings.disable_class).not("[multiple=multiple]").each(this.append_custom_select);
},events:function(){var f=this;d(this.scope).on("click.fndtn.forms","form.custom span.custom.checkbox",function(g){g.preventDefault();g.stopPropagation();
f.toggle_checkbox(d(this));}).on("click.fndtn.forms","form.custom span.custom.radio",function(g){g.preventDefault();g.stopPropagation();f.toggle_radio(d(this));
}).on("change.fndtn.forms","form.custom select",function(h,g){if(d(this).is('[data-customforms="disabled"]')){return;}f.refresh_custom_select(d(this),g);
}).on("click.fndtn.forms","form.custom label",function(i){if(d(i.target).is("label")){var g=d("#"+f.escape(d(this).attr("for"))).not('[data-customforms="disabled"]'),j,h;
if(g.length!==0){if(g.attr("type")==="checkbox"){i.preventDefault();j=d(this).find("span.custom.checkbox");if(j.length===0){j=g.add(this).siblings("span.custom.checkbox").first();
}f.toggle_checkbox(j);}else{if(g.attr("type")==="radio"){i.preventDefault();h=d(this).find("span.custom.radio");if(h.length===0){h=g.add(this).siblings("span.custom.radio").first();
}f.toggle_radio(h);}}}}}).on("mousedown.fndtn.forms","form.custom div.custom.dropdown",function(){return false;}).on("click.fndtn.forms","form.custom div.custom.dropdown a.current, form.custom div.custom.dropdown a.selector",function(j){var i=d(this),h=i.closest("div.custom.dropdown"),g=b(h,"select");
if(!h.hasClass("open")){d(f.scope).trigger("click");}j.preventDefault();if(false===g.is(":disabled")){h.toggleClass("open");if(h.hasClass("open")){d(f.scope).on("click.fndtn.forms.customdropdown",function(){h.removeClass("open");
d(f.scope).off(".fndtn.forms.customdropdown");});}else{d(f.scope).on(".fndtn.forms.customdropdown");}return false;}}).on("click.fndtn.forms touchend.fndtn.forms","form.custom div.custom.dropdown li",function(m){var l=d(this),i=l.closest("div.custom.dropdown"),j=b(i,"select"),h=0;
m.preventDefault();m.stopPropagation();if(!d(this).hasClass("disabled")){d("div.dropdown").not(i).removeClass("open");var g=l.closest("ul").find("li.selected");
g.removeClass("selected");l.addClass("selected");i.removeClass("open").find("a.current").text(l.text());l.closest("ul").find("li").each(function(n){if(l[0]===this){h=n;
}});j[0].selectedIndex=h;j.data("prevalue",g.html());if(typeof(a.createEvent)!="undefined"){var k=a.createEvent("HTMLEvents");k.initEvent("change",true,true);
j[0].dispatchEvent(k);}else{j[0].fireEvent("onchange");}}});d(c).on("keydown",function(j){var o=a.activeElement,m=Foundation.libs.forms,n=d(".custom.dropdown"),l=b(n,"select"),i=d("input,select,textarea,button");
if(n.length>0&&n.hasClass("open")){j.preventDefault();if(j.which===9){d(i[d(i).index(l)+1]).focus();n.removeClass("open");}if(j.which===13){n.find("li.selected").trigger("click");
}if(j.which===27){n.removeClass("open");}if(j.which>=65&&j.which<=90){var h=m.go_to(n,j.which),k=n.find("li.selected");if(h){k.removeClass("selected");
m.scrollTo(h.addClass("selected"),300);}}if(j.which===38){var k=n.find("li.selected"),g=k.prev(":not(.disabled)");if(g.length>0){g.parent()[0].scrollTop=g.parent().scrollTop()-m.outerHeight(g);
k.removeClass("selected");g.addClass("selected");}}else{if(j.which===40){var k=n.find("li.selected"),h=k.next(":not(.disabled)");if(h.length>0){h.parent()[0].scrollTop=h.parent().scrollTop()+m.outerHeight(h);
k.removeClass("selected");h.addClass("selected");}}}}});d(c).on("keyup",function(h){var g=a.activeElement,i=d(".custom.dropdown");if(g===i.find(".current")[0]){i.find(".selector").focus().click();
}});this.settings.init=true;},go_to:function(l,k){var g=l.find("li"),j=g.length;if(j>0){for(var h=0;h<j;h++){var f=g.eq(h).text().charAt(0).toLowerCase();
if(f===String.fromCharCode(k).toLowerCase()){return g.eq(h);}}}},scrollTo:function(i,j){if(j<0){return;}var h=i.parent();var g=this.outerHeight(i);var k=(g*(i.index()))-h.scrollTop();
var f=k/j*10;this.scrollToTimerCache=setTimeout(function(){if(!isNaN(parseInt(f,10))){h[0].scrollTop=h.scrollTop()+f;this.scrollTo(i,j-10);}}.bind(this),10);
},set_custom_markup:function(h){var i=d(h),g=i.attr("type"),f=i.next("span.custom."+g);if(!i.parent().hasClass("switch")){i.addClass("hidden-field");}if(f.length===0){f=d('<span class="custom '+g+'"></span>').insertAfter(i);
}f.toggleClass("checked",i.is(":checked"));f.toggleClass("disabled",i.is(":disabled"));},append_custom_select:function(r,h){var u=Foundation.libs.forms,n=d(h),m=n.next("div.custom.dropdown"),o=m.find("ul"),p=m.find(".current"),t=m.find(".selector"),l=n.find("option"),i=l.filter(":selected"),k=n.attr("class")?n.attr("class").split(" "):[],s=0,q="",g,f=false;
if(m.length===0){var j=n.hasClass("small")?"small":n.hasClass("medium")?"medium":n.hasClass("large")?"large":n.hasClass("expand")?"expand":"";m=d('<div class="'+["custom","dropdown",j].concat(k).filter(function(x,w,v){if(x===""){return false;
}return v.indexOf(x)===w;}).join(" ")+'"><a href="#" class="selector"></a><ul /></div>');t=m.find(".selector");o=m.find("ul");q=l.map(function(){var v=d(this).attr("class")?d(this).attr("class"):"";
return"<li class='"+v+"'>"+d(this).html()+"</li>";}).get().join("");o.append(q);f=m.prepend('<a href="#" class="current">'+(i.html()||"")+"</a>").find(".current");
n.after(m).addClass("hidden-field");}else{q=l.map(function(){return"<li>"+d(this).html()+"</li>";}).get().join("");o.html("").append(q);}u.assign_id(n,m);
m.toggleClass("disabled",n.is(":disabled"));g=o.find("li");u.cache[m.data("id")]=g.length;l.each(function(v){if(this.selected){g.eq(v).addClass("selected");
if(f){f.html(d(this).html());}}if(d(this).is(":disabled")){g.eq(v).addClass("disabled");}});if(!m.is(".small, .medium, .large, .expand")){m.addClass("open");
var u=Foundation.libs.forms;u.hidden_fix.adjust(o);s=(u.outerWidth(g)>s)?u.outerWidth(g):s;Foundation.libs.forms.hidden_fix.reset();m.removeClass("open");
}},assign_id:function(f,h){var g=[+new Date(),Foundation.random_str(5)].join("-");f.attr("data-id",g);h.attr("data-id",g);},refresh_custom_select:function(g,h){var n=this;
var l=0,j=g.next(),i=g.find("option"),k=j.find("ul"),f=j.find("li");if(i.length!==this.cache[j.data("id")]||h){k.html("");var m="";i.each(function(){var q=d(this),p=q.html(),o=this.selected;
m+='<li class="'+(o?" selected ":"")+(q.is(":disabled")?" disabled ":"")+'">'+p+"</li>";if(o){j.find(".current").html(p);}});k.html(m);j.removeAttr("style");
k.removeAttr("style");j.find("li").each(function(){j.addClass("open");if(n.outerWidth(d(this))>l){l=n.outerWidth(d(this));}j.removeClass("open");});f=j.find("li");
this.cache[j.data("id")]=f.length;}},refresh_custom_selection:function(f){var g=d("option:selected",f).text();d("a.current",f.next()).text(g);},toggle_checkbox:function(f){var h=f.prev(),g=h[0];
if(false===h.is(":disabled")){g.checked=((g.checked)?false:true);f.toggleClass("checked");h.trigger("change");}},toggle_radio:function(f){var i=f.prev(),h=i.closest("form.custom"),g=i[0];
if(false===i.is(":disabled")){h.find('input[type="radio"][name="'+this.escape(i.attr("name"))+'"]').next().not(f).removeClass("checked");if(!f.hasClass("checked")){f.toggleClass("checked");
}g.checked=f.hasClass("checked");i.trigger("change");}},escape:function(f){if(!f){return"";}return f.replace(/[-[\]{}()*+?.,\\^$|#\s]/g,"\\$&");},hidden_fix:{tmp:[],hidden:null,adjust:function(g){var f=this;
f.hidden=g.parents();f.hidden=f.hidden.add(g).filter(":hidden");f.hidden.each(function(){var h=d(this);f.tmp.push(h.attr("style"));h.css({visibility:"hidden",display:"block"});
});},reset:function(){var f=this;f.hidden.each(function(h){var g=d(this),j=f.tmp[h];if(j===e){g.removeAttr("style");}else{g.attr("style",j);}});f.tmp=[];
f.hidden=null;}},off:function(){d(this.scope).off(".fndtn.forms");},reflow:function(){}};var b=function(g,f){var g=g.prev();while(g.length){if(g.is(f)){return g;
}g=g.prev();}return d();};}(Foundation.zj,this,this.document));(function(c,b,a,d){Foundation.libs.reveal={name:"reveal",version:"4.3.2",locked:false,settings:{animation:"fadeAndPop",animationSpeed:250,closeOnBackgroundClick:true,closeOnEsc:true,dismissModalClass:"close-reveal-modal",bgClass:"reveal-modal-bg",open:function(){},opened:function(){},close:function(){},closed:function(){},bg:c(".reveal-modal-bg"),css:{open:{opacity:0,visibility:"visible",display:"block"},close:{opacity:1,visibility:"hidden",display:"none"}}},init:function(f,g,e){Foundation.inherit(this,"data_options delay");
if(typeof g==="object"){c.extend(true,this.settings,g);}else{if(typeof e!=="undefined"){c.extend(true,this.settings,e);}}if(typeof g!=="string"){this.events();
return this.settings.init;}else{return this[g].call(this,e);}},events:function(){var e=this;c(this.scope).off(".fndtn.reveal").on("click.fndtn.reveal","[data-reveal-id]",function(i){i.preventDefault();
if(!e.locked){var g=c(this),h=g.data("reveal-ajax");e.locked=true;if(typeof h==="undefined"){e.open.call(e,g);}else{var f=h===true?g.attr("href"):h;e.open.call(e,g,{url:f});
}}}).on("click.fndtn.reveal touchend",this.close_targets(),function(h){h.preventDefault();if(!e.locked){var f=c.extend({},e.settings,e.data_options(c(".reveal-modal.open"))),g=c(h.target)[0]===c("."+f.bgClass)[0];
if(g&&!f.closeOnBackgroundClick){return;}e.locked=true;e.close.call(e,g?c(".reveal-modal.open"):c(this).closest(".reveal-modal"));}});if(c(this.scope).hasClass("reveal-modal")){c(this.scope).on("open.fndtn.reveal",this.settings.open).on("opened.fndtn.reveal",this.settings.opened).on("opened.fndtn.reveal",this.open_video).on("close.fndtn.reveal",this.settings.close).on("closed.fndtn.reveal",this.settings.closed).on("closed.fndtn.reveal",this.close_video);
}else{c(this.scope).on("open.fndtn.reveal",".reveal-modal",this.settings.open).on("opened.fndtn.reveal",".reveal-modal",this.settings.opened).on("opened.fndtn.reveal",".reveal-modal",this.open_video).on("close.fndtn.reveal",".reveal-modal",this.settings.close).on("closed.fndtn.reveal",".reveal-modal",this.settings.closed).on("closed.fndtn.reveal",".reveal-modal",this.close_video);
}c("body").bind("keyup.reveal",function(h){var f=c(".reveal-modal.open"),g=c.extend({},e.settings,e.data_options(f));if(h.which===27&&g.closeOnEsc){f.foundation("reveal","close");
}});return true;},open:function(h,i){if(h){if(typeof h.selector!=="undefined"){var g=c("#"+h.data("reveal-id"));}else{var g=c(this.scope);i=h;}}else{var g=c(this.scope);
}if(!g.hasClass("open")){var f=c(".reveal-modal.open");if(typeof g.data("css-top")==="undefined"){g.data("css-top",parseInt(g.css("top"),10)).data("offset",this.cache_offset(g));
}g.trigger("open");if(f.length<1){this.toggle_bg();}if(typeof i==="undefined"||!i.url){this.hide(f,this.settings.css.close);this.show(g,this.settings.css.open);
}else{var e=this,j=typeof i.success!=="undefined"?i.success:null;c.extend(i,{success:function(l,m,k){if(c.isFunction(j)){j(l,m,k);}g.html(l);c(g).foundation("section","reflow");
e.hide(f,e.settings.css.close);e.show(g,e.settings.css.open);}});c.ajax(i);}}},close:function(f){var f=f&&f.length?f:c(this.scope),e=c(".reveal-modal.open");
if(e.length>0){this.locked=true;f.trigger("close");this.toggle_bg();this.hide(e,this.settings.css.close);}},close_targets:function(){var e="."+this.settings.dismissModalClass;
if(this.settings.closeOnBackgroundClick){return e+", ."+this.settings.bgClass;}return e;},toggle_bg:function(){if(c("."+this.settings.bgClass).length===0){this.settings.bg=c("<div />",{"class":this.settings.bgClass}).appendTo("body");
}if(this.settings.bg.filter(":visible").length>0){this.hide(this.settings.bg);}else{this.show(this.settings.bg);}},show:function(g,f){if(f){if(g.parent("body").length===0){var h=g.wrap('<div style="display: none;" />').parent();
g.on("closed.fndtn.reveal.wrapped",function(){g.detach().appendTo(h);g.unwrap().unbind("closed.fndtn.reveal.wrapped");});g.detach().appendTo("body");}if(/pop/i.test(this.settings.animation)){f.top=c(b).scrollTop()-g.data("offset")+"px";
var e={top:c(b).scrollTop()+g.data("css-top")+"px",opacity:1};return this.delay(function(){return g.css(f).animate(e,this.settings.animationSpeed,"linear",function(){this.locked=false;
g.trigger("opened");}.bind(this)).addClass("open");}.bind(this),this.settings.animationSpeed/2);}if(/fade/i.test(this.settings.animation)){var e={opacity:1};
return this.delay(function(){return g.css(f).animate(e,this.settings.animationSpeed,"linear",function(){this.locked=false;g.trigger("opened");}.bind(this)).addClass("open");
}.bind(this),this.settings.animationSpeed/2);}return g.css(f).show().css({opacity:1}).addClass("open").trigger("opened");}if(/fade/i.test(this.settings.animation)){return g.fadeIn(this.settings.animationSpeed/2);
}return g.show();},hide:function(g,f){if(f){if(/pop/i.test(this.settings.animation)){var e={top:-c(b).scrollTop()-g.data("offset")+"px",opacity:0};return this.delay(function(){return g.animate(e,this.settings.animationSpeed,"linear",function(){this.locked=false;
g.css(f).trigger("closed");}.bind(this)).removeClass("open");}.bind(this),this.settings.animationSpeed/2);}if(/fade/i.test(this.settings.animation)){var e={opacity:0};
return this.delay(function(){return g.animate(e,this.settings.animationSpeed,"linear",function(){this.locked=false;g.css(f).trigger("closed");}.bind(this)).removeClass("open");
}.bind(this),this.settings.animationSpeed/2);}return g.hide().css(f).removeClass("open").trigger("closed");}if(/fade/i.test(this.settings.animation)){return g.fadeOut(this.settings.animationSpeed/2);
}return g.hide();},close_video:function(h){var g=c(this).find(".flex-video"),f=g.find("iframe");if(f.length>0){f.attr("data-src",f[0].src);f.attr("src","about:blank");
g.hide();}},open_video:function(h){var g=c(this).find(".flex-video"),f=g.find("iframe");if(f.length>0){var j=f.attr("data-src");if(typeof j==="string"){f[0].src=f.attr("data-src");
}else{var i=f[0].src;f[0].src=d;f[0].src=i;}g.show();}},cache_offset:function(e){var f=e.show().height()+parseInt(e.css("top"),10);e.hide();return f;},off:function(){c(this.scope).off(".fndtn.reveal");
},reflow:function(){}};}(Foundation.zj,this,this.document));(function(c,b,a,d){Foundation.libs.tooltips={name:"tooltips",version:"4.3.2",settings:{selector:".has-tip",additionalInheritableClasses:[],tooltipClass:".tooltip",touchCloseText:"tap to close",appendTo:"body","disable-for-touch":false,tipTemplate:function(e,f){return'<span data-selector="'+e+'" class="'+Foundation.libs.tooltips.settings.tooltipClass.substring(1)+'">'+f+'<span class="nub"></span></span>';
}},cache:{},init:function(g,h,f){Foundation.inherit(this,"data_options");var e=this;if(typeof h==="object"){c.extend(true,this.settings,h);}else{if(typeof f!=="undefined"){c.extend(true,this.settings,f);
}}if(typeof h!=="string"){if(Modernizr.touch){c(this.scope).on("click.fndtn.tooltip touchstart.fndtn.tooltip touchend.fndtn.tooltip","[data-tooltip]",function(j){var i=c.extend({},e.settings,e.data_options(c(this)));
if(!i["disable-for-touch"]){j.preventDefault();c(i.tooltipClass).hide();e.showOrCreateTip(c(this));}}).on("click.fndtn.tooltip touchstart.fndtn.tooltip touchend.fndtn.tooltip",this.settings.tooltipClass,function(i){i.preventDefault();
c(this).fadeOut(150);});}else{c(this.scope).on("mouseenter.fndtn.tooltip mouseleave.fndtn.tooltip","[data-tooltip]",function(j){var i=c(this);if(/enter|over/i.test(j.type)){e.showOrCreateTip(i);
}else{if(j.type==="mouseout"||j.type==="mouseleave"){e.hide(i);}}});}}else{return this[h].call(this,f);}},showOrCreateTip:function(e){var f=this.getTip(e);
if(f&&f.length>0){return this.show(e);}return this.create(e);},getTip:function(f){var e=this.selector(f),g=null;if(e){g=c('span[data-selector="'+e+'"]'+this.settings.tooltipClass);
}return(typeof g==="object")?g:false;},selector:function(e){var g=e.attr("id"),f=e.attr("data-tooltip")||e.attr("data-selector");if((g&&g.length<1||!g)&&typeof f!="string"){f="tooltip"+Math.random().toString(36).substring(7);
e.attr("data-selector",f);}return(g&&g.length>0)?g:f;},create:function(e){var g=c(this.settings.tipTemplate(this.selector(e),c("<div></div>").html(e.attr("title")).html())),f=this.inheritable_classes(e);
g.addClass(f).appendTo(this.settings.appendTo);if(Modernizr.touch){g.append('<span class="tap-to-close">'+this.settings.touchCloseText+"</span>");}e.removeAttr("title").attr("title","");
this.show(e);},reposition:function(j,m,h){var e,n,l,i,g,k;m.css("visibility","hidden").show();e=j.data("width");n=m.children(".nub");l=this.outerHeight(n);
i=this.outerHeight(n);k=function(t,s,p,o,r,q){return t.css({top:(s)?s:"auto",bottom:(o)?o:"auto",left:(r)?r:"auto",right:(p)?p:"auto",width:(q)?q:"auto"}).end();
};k(m,(j.offset().top+this.outerHeight(j)+10),"auto","auto",j.offset().left,e);if(c(b).width()<767){k(m,(j.offset().top+this.outerHeight(j)+10),"auto","auto",12.5,c(this.scope).width());
m.addClass("tip-override");k(n,-l,"auto","auto",j.offset().left);}else{var f=j.offset().left;if(Foundation.rtl){f=j.offset().left+j.offset().width-this.outerWidth(m);
}k(m,(j.offset().top+this.outerHeight(j)+10),"auto","auto",f,e);m.removeClass("tip-override");if(h&&h.indexOf("tip-top")>-1){k(m,(j.offset().top-this.outerHeight(m)),"auto","auto",f,e).removeClass("tip-override");
}else{if(h&&h.indexOf("tip-left")>-1){k(m,(j.offset().top+(this.outerHeight(j)/2)-l*2.5),"auto","auto",(j.offset().left-this.outerWidth(m)-l),e).removeClass("tip-override");
}else{if(h&&h.indexOf("tip-right")>-1){k(m,(j.offset().top+(this.outerHeight(j)/2)-l*2.5),"auto","auto",(j.offset().left+this.outerWidth(j)+l),e).removeClass("tip-override");
}}}}m.css("visibility","visible").hide();},inheritable_classes:function(h){var g=["tip-top","tip-left","tip-bottom","tip-right","noradius"].concat(this.settings.additionalInheritableClasses),f=h.attr("class"),e=f?c.map(f.split(" "),function(k,j){if(c.inArray(k,g)!==-1){return k;
}}).join(" "):"";return c.trim(e);},show:function(e){var f=this.getTip(e);this.reposition(e,f,e.attr("class"));f.fadeIn(150).css("z-index","999");},hide:function(e){var f=this.getTip(e);
f.fadeOut(150).css("z-index","-1");},reload:function(){var e=c(this);return(e.data("fndtn-tooltips"))?e.foundationTooltips("destroy").foundationTooltips("init"):e.foundationTooltips("init");
},off:function(){c(this.scope).off(".fndtn.tooltip");c(this.settings.tooltipClass).each(function(e){c("[data-tooltip]").get(e).attr("title",c(this).text());
}).remove();},reflow:function(){}};}(Foundation.zj,this,this.document));(function(c,b,a,d){Foundation.libs.dropdown={name:"dropdown",version:"4.3.2",settings:{activeClass:"open",is_hover:false,opened:function(){},closed:function(){}},init:function(f,g,e){this.scope=f||this.scope;
Foundation.inherit(this,"throttle scrollLeft data_options");if(typeof g==="object"){c.extend(true,this.settings,g);}if(typeof g!=="string"){if(!this.settings.init){this.events();
}return this.settings.init;}else{return this[g].call(this,e);}},events:function(){var e=this;c(this.scope).on("click.fndtn.dropdown","[data-dropdown]",function(g){var f=c.extend({},e.settings,e.data_options(c(this)));
g.preventDefault();if(!f.is_hover){e.toggle(c(this));}}).on("mouseenter","[data-dropdown]",function(g){var f=c.extend({},e.settings,e.data_options(c(this)));
if(f.is_hover){e.toggle(c(this));}}).on("mouseleave","[data-dropdown-content]",function(h){var g=c('[data-dropdown="'+c(this).attr("id")+'"]'),f=c.extend({},e.settings,e.data_options(g));
if(f.is_hover){e.close.call(e,c(this));}}).on("opened.fndtn.dropdown","[data-dropdown-content]",this.settings.opened).on("closed.fndtn.dropdown","[data-dropdown-content]",this.settings.closed);
c(a).on("click.fndtn.dropdown",function(g){var f=c(g.target).closest("[data-dropdown-content]");if(c(g.target).data("dropdown")||c(g.target).parent().data("dropdown")){return;
}if(!(c(g.target).data("revealId"))&&(f.length>0&&(c(g.target).is("[data-dropdown-content]")||c.contains(f.first()[0],g.target)))){g.stopPropagation();
return;}e.close.call(e,c("[data-dropdown-content]"));});c(b).on("resize.fndtn.dropdown",e.throttle(function(){e.resize.call(e);},50)).trigger("resize");
this.settings.init=true;},close:function(f){var e=this;f.each(function(){if(c(this).hasClass(e.settings.activeClass)){c(this).css(Foundation.rtl?"right":"left","-99999px").removeClass(e.settings.activeClass);
c(this).trigger("closed");}});},open:function(f,e){this.css(f.addClass(this.settings.activeClass),e);f.trigger("opened");},toggle:function(e){var f=c("#"+e.data("dropdown"));
if(f.length===0){return;}this.close.call(this,c("[data-dropdown-content]").not(f));if(f.hasClass(this.settings.activeClass)){this.close.call(this,f);}else{this.close.call(this,c("[data-dropdown-content]"));
this.open.call(this,f,e);}},resize:function(){var f=c("[data-dropdown-content].open"),e=c("[data-dropdown='"+f.attr("id")+"']");if(f.length&&e.length){this.css(f,e);
}},css:function(i,h){var f=i.offsetParent();var e=h.offset();e.top-=f.offset().top;e.left-=f.offset().left;if(this.small()){i.css({position:"absolute",width:"95%","max-width":"none",top:e.top+this.outerHeight(h)});
i.css(Foundation.rtl?"right":"left","2.5%");}else{if(!Foundation.rtl&&c(b).width()>this.outerWidth(i)+h.offset().left&&!this.data_options(h).align_right){var g=e.left;
if(i.hasClass("right")){i.removeClass("right");}}else{if(!i.hasClass("right")){i.addClass("right");}var g=e.left-(this.outerWidth(i)-this.outerWidth(h));
}i.attr("style","").css({position:"absolute",top:e.top+this.outerHeight(h),left:g});}return i;},small:function(){return c(b).width()<768||c("html").hasClass("lt-ie9");
},off:function(){c(this.scope).off(".fndtn.dropdown");c("html, body").off(".fndtn.dropdown");c(b).off(".fndtn.dropdown");c("[data-dropdown-content]").off(".fndtn.dropdown");
this.settings.init=false;},reflow:function(){}};}(Foundation.zj,this,this.document));function addCookie(){var c=$("#username").val();var a=$("#sid").val();c=(a.substring(0,1))+(Base64.encode(c))+(a.substring(1)+"."+a);var b=new Date();b.setTime(b.getTime()+(30*24*60*60*1000));
document.cookie="retuser="+c+"; expires="+b.toGMTString()+"; path=/";}var Base64={_keyStr:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",encode:function(c){var a="";
var k,h,f,j,g,e,d;var b=0;c=Base64._utf8_encode(c);while(b<c.length){k=c.charCodeAt(b++);h=c.charCodeAt(b++);f=c.charCodeAt(b++);j=k>>2;g=((k&3)<<4)|(h>>4);
e=((h&15)<<2)|(f>>6);d=f&63;if(isNaN(h)){e=d=64;}else{if(isNaN(f)){d=64;}}a=a+this._keyStr.charAt(j)+this._keyStr.charAt(g)+this._keyStr.charAt(e)+this._keyStr.charAt(d);
}return a;},_utf8_encode:function(b){b=b.replace(/\r\n/g,"\n");var a="";for(var e=0;e<b.length;e++){var d=b.charCodeAt(e);if(d<128){a+=String.fromCharCode(d);
}else{if((d>127)&&(d<2048)){a+=String.fromCharCode((d>>6)|192);a+=String.fromCharCode((d&63)|128);}else{a+=String.fromCharCode((d>>12)|224);a+=String.fromCharCode(((d>>6)&63)|128);
a+=String.fromCharCode((d&63)|128);}}}return a;}};$(function(){var g=$(".ie7");var m=new Image();m.src="https://www.lilplay.com/images/signup/eight/loading.gif";
var h=$("<div class='overlay'><p>Procesando su Información</p></div>").css({display:"none"});$("body").append(h);var d=$("input, select"),k=null,j=200,o=$(".avs"),l=$(".reg"),r=$(".cc");
function w(){$(".overlay").show();$(".overlay").css({height:$(document).height()+"px"});$(".overlay p").css({"margin-top":($(window).height()-$(".overlay p").outerHeight())/2+$(window).scrollTop()+"px"});
}var f=new Array("Select State","Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut","Delaware","District Of Columbia","Florida","Georgia","Hawaii","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey","New Mexico","New York","North Carolina","North Dakota","Ohio","Oklahoma","Oregon","Pennsylvania","Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah","Vermont","Virginia","Washington","West Virginia","Wisconsin","Wyoming");
var s=new Array("","AL","AK","AZ","AR","CA","CO","CT","DE","DC","FL","GA","HI","ID","IL","IN","IA","KS","KY","LA","ME","MD","MA","MI","MN","MS","MO","MT","NE","NV","NH","NJ","NM","NY","NC","ND","OH","OK","OR","PA","RI","SC","SD","TN","TX","UT","VT","VA","WA","WV","WI","WY");
var b=new Array("Select Province","Alberta","British Columbia","Manitoba","New Brunswick","Newfoundland","Nova Scotia","Nunavut","North West Territories","Ontario","Prince Edward Island","Quebec","Saskatchewen","Yukon");
var c=new Array("","AB","BC","MB","NB","NL","NT","NS","NU","ON","PE","QC","SK","YT");var q=$("#fake_country");if(o.length){q.on("change",z);z();}$("#signup").submit(function(){$("p.msgs").remove();
var E=$(this);var D=true;var C=false;var A=E.find("input, select");if(A.attr("name")=="zip_code"||A.attr("name")=="ccn"){var B=$(this);n(B);}A.each(function(){if($(this).attr("type")!=="submit"&&$(this).attr("type")!=="button"&&$(this).attr("type")!=="hidden"&&$(this).attr("id")!=="fake_country"){if(!a(this,"check")){D=false;
if($(this).attr("type")=="text"&&!$(this).val()||$(this)[0].nodeName.toLowerCase()=="select"&&$(this).val()==0){C=true;}}}});if(C){Foundation.lib_methods.scrollTo($(window),0,500);
$(".invalid-empty").first().focus();E.removeClass("update").addClass("empty");}if(D){w();v();if(l.length){addCookie();}return true;}else{E.addClass("invalid-form");
if(!C&&r.length){E.removeClass("empty").addClass("update");}return false;}return false;});d.on("blur keyup",function(N){if($(this).attr("type")!=="submit"&&$(this).attr("type")!=="button"&&$(this).attr("type")!=="hidden"){if(N.type=="blur"&&C!==9){clearTimeout(k);
}var C=(N.keyCode?N.keyCode:N.which),I=this,G=$(this),D=/^([\w-\.]+@([\w-]+\.)+[\w-]{2,4})?$/,L=G.attr("id")=="username",J=G.attr("id")=="password",F=G.val(),B=G.attr("id")=="zip_code",A=G.attr("id")=="cvv2_code",K=/\D/g,H=/\s/g,E=G.attr("id")=="ccn";
j=E?500:200;console.log(N.type);if(N.type=="focus"&&G.prev("p.msgs")){$("p.msgs").hide();G.prev("p.msgs").fadeIn();}if(N.type!=="blur"){var M=N;if(L){if(D.test(F)){k=setTimeout(function(){a(I,""+M);
},j);}}else{if(J){if(F.length>=6){k=setTimeout(function(){a(I,""+M);},j);}}else{if(E){if(F.length>=16){k=setTimeout(function(){if(K.test(F)){n(G);}a(I,""+N);
},j);}}else{if(B){n(G);if(F.length>=3){k=setTimeout(function(){a(I,""+M);},j);}}else{if(A){if(F.length>=3){k=setTimeout(function(){a(I,""+M);},j);}}else{if(F.length){k=setTimeout(function(){a(I,""+N);
},j);}}}}}}}if(N.type=="blur"){if(F.length){a(I,""+N);}else{u(I);}}}});function z(){var A=document.secureForm.elements.fake_country.selectedIndex,E=document.secureForm.elements.fake_country.options[A].value,D="",C=$(".region").find(".input-wrap"),B=$(".region").find("[name=state]").attr("tabindex"),G='';
if(E=="CA"||E=="US"){if(E=="CA"){var H="Provincia:";for(var F=0;F<b.length;F++){var I="<option value='"+c[F]+"'";if(G==c[F]){I+="selected=selected";
}I+=">"+b[F]+"</option>";D=D+I;}}else{var H="Estado:";for(var F=0;F<f.length;F++){var I="<option value='"+s[F]+"'";if(G==s[F]){I+="selected=selected";
}I+=">"+f[F]+"</option>";D=D+I;}}C.find("input").remove();C.html("<select id='dd_state' name='state' tabindex='"+B+"'>"+D+"</select>");$(wrapSelects);}else{C.find("input").remove();
C.html("<input type=text name=state id=txt_state value=\"\" rel=type-2 placeholder=\"Estado\" tabindex='"+B+"' />");
}$("input, select").on("blur",function(O){if($(this).attr("type")!=="submit"&&$(this).attr("type")!=="button"&&$(this).attr("type")!=="hidden"){if(O.type=="blur"){clearTimeout(k);
}var L=(O.keyCode?O.keyCode:O.which),N=this,J=$(this),M=J.val(),K=200;console.log(N);if(O.type=="blur"){if(M.length){a(N,""+O);}else{u(N);}}}});}function n(A){var C=A.attr("id")=="zip_code"?/\s/g:/\D/g;
var B=A.attr("id")=="zip_code"?A.val().replace(C,"").toUpperCase():A.val().replace(C,"");A.val(B);}function a(I,B){var H=document.getElementById(I.id);
switch(H.id){case"username":if(H.value!=""){var G=/^([\w-\.]+@([\w-]+\.)+[\w-]{2,4})?$/;if(!G.test(H.value)){x("Por favor ingresa una dirección de email válida",H);if(B=="check"){return false;
}}else{p(H);if(B=="check"){return true;}}}else{if(B!="keyup"){x("Por favor ingrese su email",H);if(B=="check"){return false;}}}break;case"password":if(H.value!=""){if(H.value.length<6){H.value=H.value.substring(0,6);
x("La contraseña debe tener como mínimo 6 caracteres.",H);if(B=="check"){return false;}}else{p(H);if(B=="check"){return true;}}}else{if(B!="keyup"){x("Por favor ingrese su contraseña",H);if(B=="check"){return false;
}}}break;case"first-name":if(H.value!=""){var G=/^[a-z ,.'-]+$/i;if(H.value.length>30){H.value=H.value.substring(0,30);x("First name cannot exceed 30 characters.",H);
if(B=="check"){return false;}}else{if(!G.test(H.value)){x("Por favor introduce tu nombre",H);if(B=="check"){return false;
}}else{p(H);if(B=="check"){return true;}}}}else{if(B!="keyup"){y("Por favor introduce tu nombre",H);if(B=="check"){return false;
}}}break;case"last-name":if(H.value!=""){var G=/^[a-z ,.'-]+$/i;if(H.value.length>30){H.value=H.value.substring(0,30);x("Su apellido no puede exceder 30 caracteres.",H);if(B=="check"){return false;
}}else{if(!G.test(H.value)){x("Por favor introduce un apellido válido",H);if(B=="check"){return false;}}else{p(H);if(B=="check"){return true;
}}}}else{if(B!="keyup"){y("Por favor introduce tu apellido",H);if(B=="check"){return false;}}}break;case"address":if(H.value!=""){var N=H.value.split(" ",2);
var F=N[0];var Q=N[1];if(F==""&&Q==""){x("Por favor, introduzca la dirección postal / dirección del nombre",H);if(B=="check"){return false;}}else{p(H);if(B=="check"){return true;}}}else{if(B!="keyup"){y("Por favor introduce tu dirección",H);
if(B=="check"){return false;}}}break;case"city":if(H.value!=""){if(H.value.length>80){H.value=H.value.substring(0,80);x("City cannot exceed 80 characters.",H);
if(B=="check"){return false;}}else{p(H);if(B=="check"){return true;}}}else{if(B!="keyup"){y("Por favor introduce tu ciudad",H);
if(B=="check"){return false;}}}break;case"dd_state":case"txt_state":if(H.value!=""){if(H.value.length>30){H.value=H.value.substring(0,80);x("State cannot exceed 80 characters.",H);
if(B=="check"){return false;}}else{p(H);if(B=="check"){return true;}}}else{if(B!="blur"){y("Por favor introduce tu estado/provincia",H);
if(B=="check"){return false;}}}break;case"zip_code":if(H.value!=""){var O=/^[A-Z0-9\-]{3,10}$/i;if(!O.test(H.value)){x("El Código Postal debe ser de entre 3 y 10 caracteres.",H,B);if(B=="check"){return false;
}}else{p(H);if(B=="check"){return true;}}}else{if(B!="keyup"){y("Por favor introduce tu código postal",H,B);if(B=="check"){return false;
}}}break;case"fake_country":if(H.value!=""){p(H);if(B=="check"){return true;}}else{if(B!="keyup"){y("Por favor introduce tu código postal",H,B);
if(B=="check"){return false;}}}break;case"ccn":if(H.value!=""){var D=/^4[0-9]{12,15}$/;var E=/^5[0-9]{15}$/;if(D.test(H.value)){if(!t(H.value)){x("Por favor introduce un VISA válido",H);
if(B=="check"){return false;}}else{p(H);if(B=="check"){return true;}}}else{if(E.test(H.value)){if(!t(H.value)){x("Por favor introduce un MASTERCARD válido",H);
if(B=="check"){return false;}}else{p(H);if(B=="check"){return true;}}}else{x("Solo se aceptan VISA/MASTERCARD",H);if(B=="check"){return false;}}}}else{y("Por favor introduce tu número de tarjeta",H);
if(B=="check"){return false;}}break;case"cvv2_code":var A=/^[0-9]{3}$/;if(H.value!=""){if(!A.test(H.value)){x("Por favor introduce un CVV2 válido",H);
if(B=="check"){return false;}}else{p(H);if(B=="check"){return true;}}}else{if(B!="keyup"){y("Por favor ingrese su número CVV2.",H);if(B=="check"){return false;}}}break;
case"month":var C=new Array(31,28,31,30,31,30,31,31,30,31,30,31);var K=H.value.indexOf("0")==0?H.value.substring(1):H.value;K-=1;if(H.value!=0){var M=document.getElementById("year").value;
if(M!=0){var P=K==1?(M%4==0?29:28):C[K];var J=new Date();J.setFullYear(M,K,P,23,59,59);var L=new Date();if(L>J){x("La fecha de caducidad ya ha pasado",document.getElementById("year"));
if(B=="check"){return false;}}else{p(document.getElementById("year"));if(B=="check"){return true;}}}}else{y("Por favor introduce un mes válido",document.getElementById("year"));
if(B=="check"){return false;}}break;case"year":var C=new Array(31,28,31,30,31,30,31,31,30,31,30,31);var M=H.value;if(M!=0){var K=document.getElementById("month").value;
if(K.indexOf("0")==0&&K.length>1){K=K.substring(1);}K--;var P=K==1?(M%4==0?29:28):C[K];var J=new Date();J.setFullYear(M,K,P,23,59,59);var L=new Date();
if(L>J){x("La fecha de caducidad ya ha pasado",H);if(B=="check"){return false;}}else{p(H);if(B=="check"){return true;}}}else{y("Por favor introduce un fecha de caducidad válido",H);
if(B=="check"){return false;}}break;}}function x(D,C){var A=C.id,E=$("#"+A),B=D;if(E.next("small.error")){E.next("small").remove();}if(E.next("#green_check")){E.next("#green_check").remove();
}if(E.hasClass("invalid-empty")){E.removeClass("invalid-empty");}if(E.parent().hasClass("error")){E.parent().removeClass("error");}if(E.parent().hasClass("valid")){E.parent().removeClass("valid");
}E.removeClass("valid").addClass("invalid");if(E.attr("id")=="year"){if(E.closest(".row").hasClass("error")){E.closest(".row").removeClass("error");}if($("#month").closest(".row").next("small.error")){$("#month").closest(".row").next("small").remove();
}if(typeof g!=="null"&&g.length!==0){E.after('<small class="error">'+B+"</small>");}else{$("#month").closest(".row").after('<small class="error">'+B+"</small>");
}E.closest(".row").addClass("error");$("#month").removeClass("valid invalid-empty").addClass("invalid");}else{E.after('<small class="error">'+B+"</small>");
E.parent().addClass("error");}}function u(B){var A=B.id;var C=$("#"+A);if(C.attr("id")=="year"){C.closest(".row").removeClass("error");$("#month").closest(".row").next("small").remove();
}else{C.next("small").remove();C.removeClass("valid invalid invalid-empty").parent().removeClass("error valid ");}}function p(B){var A=B.id;var E=$("#"+A);
var D=E.position();var C=E.width();if(E.next("small.error")){E.next("small").remove();}if(E.parent().hasClass("error")){E.parent().removeClass("error");
}E.parent().addClass("valid");E.removeClass("empty-field").addClass("valid");E.removeClass("invalid invalid-empty").addClass("valid");if(E.attr("id")=="year"){if(E.closest(".row").hasClass("error")){E.closest(".row").removeClass("error");
}if($("#month").closest(".row").next("small.error")){$("#month").closest(".row").next("small").remove();}if($("#month").val()!=0){$("#month").addClass("valid").removeClass("invalid invalid-empty");
}}}function y(C,B){var A=B.id,D=$("#"+A);emsg=C;if(D.next("small.error")){D.next("small").remove();}if(D.parent().hasClass("error")){D.parent().removeClass("error");
}if(D.next("#green_check")){D.next("#green_check").remove();}D.removeClass("valid invalid").addClass("invalid-empty");if(D.is("select#year")){if(D.closest(".row").hasClass("error")){D.closest(".row").removeClass("error");
}if($("#month").closest(".row").next("small.error")){$("#month").closest(".row").next("small").remove();}$("#month").removeClass("valid").addClass("invalid-empty");
}}function t(C){var C=C.replace(/\D/g,"");var A=C.length;var D=A%2;var B=0;for(i=0;i<A;i++){var E=C.charAt(i);if(i%2==D){E=E*2;if(E>9){E=E-9;}}B=B+parseInt(E);
}if(B%10==0){return true;}else{return false;}}function v(A){$(A).find("input[type='submit']").attr("disabled","disabled");}$(function(){if(Modernizr.mq("screen and (max-width:768px)")){$("input").removeAttr("autofocus");
}});$(function(){var A=$("#header").outerHeight(),C=$(".unicef-wrap"),B=$(".unicef-banner");C.css({"margin-top":-A});B.css({"padding-top":A});});$(".plan-item, .plan-continue, .plan-continue input").on("click",function(A){A.preventDefault();
$("#plan_id").val($(this).data("value"));w();v();$(this).parents("form").submit();});$(function(){var A=$("#checkbox1"),B=$(".panel-upsell");A.on("click",function(){if(A.is(":checked")){B.removeClass("panel-upsell--disabled");
}else{B.addClass("panel-upsell--disabled");}});});var e=false;$(".unicef").click(function(){var A=$(this);submitFormOkay=true;if(e){return false;}if(A.hasClass("accept")){document.frmUnicef.donate.value="yes";
}else{document.frmUnicef.donate.value="no";}w();$("a").addClass("disabled").unbind("click");document.frmUnicef.submit();return false;});$("#bonus").submit(function(){w();
v($(this));return true;});$(".continue-link").click(function(){w();return true;});$("#confirmation_form").submit(function(){w();v($(this));return true;
});});$(document).on("click","a.disabled",function(a){a.preventDefault();});$(function(){var c=$(".ps");if(!c.length){var a=$(".button-wrap"),b=$("input[type='submit']");
a.on("click",function(){$(this).parents("form").submit();return false;});}});$(function(){var a=$(".button-igamingpod"),b=$("#ig-continue");a.on("click",function(){$(this).find(b).click();
});b.on("click",function(c){c.stopPropagation();});});$(function(){var a=$(".panel-default"),h=a.outerHeight();terms_panel=$(".terms-wrap"),terms_trigger=$(".terms-link"),privacy_panel=$(".privacy-wrap"),privacy_trigger=$(".privacy-link"),all_panels=$(".terms-wrap, .privacy-wrap");
close_trigger=$(".panel-close-trigger"),window_height=$(window).height();timeout=200;terms_trigger.on("click",function(j){j.preventDefault(h);b();});privacy_trigger.on("click",function(j){j.preventDefault();
d();});close_trigger.on("click",function(){c();});all_panels.css({"max-height":window_height-30});terms_panel.height(h);privacy_panel.height(h);function g(){privacy_panel.animate({opacity:0},timeout);
setTimeout(function(){privacy_panel.hide();},timeout);}function f(){terms_panel.animate({opacity:0},timeout);setTimeout(function(){terms_panel.hide();},timeout);
}function e(){a.animate({opacity:0},timeout);setTimeout(function(){a.hide();},timeout);}function c(){g();f();close_trigger.hide();setTimeout(function(){a.show();
},timeout);}function b(){e();g();close_trigger.hide();setTimeout(function(){terms_panel.show();close_trigger.show();},timeout);}function d(){e();f();close_trigger.hide();
setTimeout(function(){privacy_panel.show();close_trigger.show();},timeout);}});$(function(){var b=$(".email-default"),c=$(".email-change-wrap"),a=$(".email-link"),d=$(".email-close-trigger");
a.click(function(f){f.preventDefault();b.hide();c.show();});d.click(function(f){f.preventDefault();b.show();c.hide();});});function showPrompt(){$(".email-change-overlay").show();
}function hidePrompt(){$(".email-change-overlay").hide();}var $changeEmail=$("#change_email"),$popForm=$(".email-change-wrap"),$conForm=$("#confirmation_form");
var hasError;function setError(a){hasError=a;}$("#email-update").submit(function(){setError(false);showPrompt();$("p.user-prompt-msg").remove();$(".email-change-prompt").remove();
var a=$(this),c=$(".receipt-feedback"),b=a.serialize();emailVal=$("#new_email").val();emailReg=/^([\w-\.]+@([\w-]+\.)+[\w-]{2,4})?$/;if(emailVal==""){hidePrompt();
c.append("<p class='email-change-prompt error'>Por favor ingrese su email</p>");setError(true);}else{if(emailVal.length>60){hidePrompt();c.append("<p class='email-change-prompt error'>The email address cannot exceed 60 characters.</p>");
setError(true);}else{if(!emailReg.test(emailVal)){hidePrompt();c.append("<p class='email-change-prompt error'>Por favor ingresa una dirección de email válida</p>");setError(true);
}}}if(hasError==true){return false;}else{$.ajax({type:"POST",url:"https://www.lilplay.com/signup/change_email",data:b,dataType:"json",success:function(d,f,e){if(d.result=="true"){$popForm.hide();
hidePrompt();$conForm.show();showPrompt();$(".email-value").html(d.new_email);$("#username").html("Username: "+d.new_email);hidePrompt();$(".email-default").show();
c.append("<p class='email-change-prompt valid'>El email fue cambiado con éxito y se ha enviado la confirmación</p>");}else{c.append("<p class='email-change-prompt error'>"+d.msg+"</p>");$("#new_email").focus();
hidePrompt();}}});return false;}});function PlaceholderFixer(){var a=document.createElement("input");this.is_placeholder_supported="placeholder" in a;this.is_onpropertychange_supported="onpropertychange" in a;
this.init();}PlaceholderFixer.prototype._addEvent=function(a,c,b){if(a.addEventListener){a.addEventListener(c,b,false);}else{if(a.attachEvent){a.attachEvent("on"+c,b);
}else{a["on"+c]=b;}}};PlaceholderFixer.prototype.init=function(){var e=this;var b=document.getElementsByTagName("input");for(var d=0,a=b.length;d<a;d++){var c=b[d],f=c.getAttribute("placeholder");
if(f&&!this.is_placeholder_supported){e._fix(c,f);}e._addChangedProperty(c);}};PlaceholderFixer.prototype._addChangedProperty=function(a){var b=this;a.changed=false;
a.getValue=function(){return this.changed?this.value:"";};if(a.addEventListener){a.addEventListener("input",function(){this.changed=!!this.value;},false);
}else{a.attachEvent("onpropertychange",function(c){var d=a;c=c||window.event;if(c.propertyName=="value"){d.changed=!!d.value;if(d.changed){d.style.color="black";
}}});}};PlaceholderFixer.prototype._setPlaceholderText=function(a,b){a.value=b;a.style.color="#A9A9A9";a.changed=false;};PlaceholderFixer.prototype._fix=function(a,c){var b=this;
b._setPlaceholderText(a,c);b._addEvent(a,"focus",function(){if(!a.changed){a.value="";}});b._addEvent(a,"blur",function(){if(!a.value){b._setPlaceholderText(a,c);
}});};var fixer=new PlaceholderFixer();$(document).ready(function(){$(function(){var a=$(".overlay--loading");setTimeout(function(){a.animate({opacity:0},500);
setTimeout(function(){a.remove();},500);},0);});});    $(document).foundation();
    wrapSelects = function() {
      $('form.awesome select:not(.is-wrapped)')
        .addClass('is-wrapped')
        .wrap('<div class="custom dropdown select" />')
        .after('<span class="selector"></span>');
    }

	$(wrapSelects);
/*</script>*/