
delete from rolopcion where id_opcion < 706 and id_opcion > 677;
delete from opcion where id_opcion < 706 and id_opcion > 677;

INSERT INTO public.opcion(id_opcion, codigo_opcion, descripcion, ruta, tipo, uri, jerarquia, estatus) VALUES (678,upper(substr(md5(trunc(random() * 9999999 + 1000000)::text), 1,6)), 'Planificación', 'N/A', 'D', 'N/A', '1', 'A');
INSERT INTO public.opcion(id_opcion, codigo_opcion, descripcion, ruta, tipo, uri, jerarquia, estatus) VALUES (679,upper(substr(md5(trunc(random() * 9999999 + 1000000)::text), 1,6)), 'Estructura Geográfica', 'N/A', 'D', 'N/A', '1.01', 'A');
INSERT INTO public.opcion(id_opcion, codigo_opcion, descripcion, ruta, tipo, uri, jerarquia, estatus) VALUES (680,upper(substr(md5(trunc(random() * 9999999 + 1000000)::text), 1,6)), 'Continentes', 'sigefirrhh/base/ubicacion/Continente', 'D', 'sigefirrhh/base/ubicacion/Continente', '1.01.01', 'A');
INSERT INTO public.opcion(id_opcion, codigo_opcion, descripcion, ruta, tipo, uri, jerarquia, estatus) VALUES (681,upper(substr(md5(trunc(random() * 9999999 + 1000000)::text), 1,6)), 'Regiones Continentales', 'sigefirrhh/base/ubicacion/RegionContinente', 'D', 'sigefirrhh/base/ubicacion/RegionContinente', '1.01.02', 'A');
INSERT INTO public.opcion(id_opcion, codigo_opcion, descripcion, ruta, tipo, uri, jerarquia, estatus) VALUES (682,upper(substr(md5(trunc(random() * 9999999 + 1000000)::text), 1,6)), 'Países', 'sigefirrhh/base/ubicacion/Pais', 'D', 'sigefirrhh/base/ubicacion/Pais', '1.01.03', 'A');
INSERT INTO public.opcion(id_opcion, codigo_opcion, descripcion, ruta, tipo, uri, jerarquia, estatus) VALUES (683,upper(substr(md5(trunc(random() * 9999999 + 1000000)::text), 1,6)), 'Estados', 'sigefirrhh/base/ubicacion/Estado', 'D', 'sigefirrhh/base/ubicacion/Estado', '1.01.04', 'A');
INSERT INTO public.opcion(id_opcion, codigo_opcion, descripcion, ruta, tipo, uri, jerarquia, estatus) VALUES (684,upper(substr(md5(trunc(random() * 9999999 + 1000000)::text), 1,6)), 'Ciudades', 'sigefirrhh/base/ubicacion/Ciudad', 'D', 'sigefirrhh/base/ubicacion/Ciudad', '1.01.05', 'A');
INSERT INTO public.opcion(id_opcion, codigo_opcion, descripcion, ruta, tipo, uri, jerarquia, estatus) VALUES (685,upper(substr(md5(trunc(random() * 9999999 + 1000000)::text), 1,6)), 'Municipios', 'sigefirrhh/base/ubicacion/Municipio', 'D', 'sigefirrhh/base/ubicacion/Municipio', '1.01.06', 'A');
INSERT INTO public.opcion(id_opcion, codigo_opcion, descripcion, ruta, tipo, uri, jerarquia, estatus) VALUES (686,upper(substr(md5(trunc(random() * 9999999 + 1000000)::text), 1,6)), 'Parroquias', 'sigefirrhh/base/ubicacion/Parroquia', 'D', 'sigefirrhh/base/ubicacion/Parroquia', '1.01.07', 'A');
INSERT INTO public.opcion(id_opcion, codigo_opcion, descripcion, ruta, tipo, uri, jerarquia, estatus) VALUES (687,upper(substr(md5(trunc(random() * 9999999 + 1000000)::text), 1,6)), 'Estructura Organizativa', 'N/A', 'D', 'N/A', '1.02', 'A');
INSERT INTO public.opcion(id_opcion, codigo_opcion, descripcion, ruta, tipo, uri, jerarquia, estatus) VALUES (688,upper(substr(md5(trunc(random() * 9999999 + 1000000)::text), 1,6)), 'Organismos', 'sigefirrhh/base/estructura/Organismo', 'D', 'sigefirrhh/base/estructura/Organismo', '1.02.01', 'A');
INSERT INTO public.opcion(id_opcion, codigo_opcion, descripcion, ruta, tipo, uri, jerarquia, estatus) VALUES (689,upper(substr(md5(trunc(random() * 9999999 + 1000000)::text), 1,6)), 'Nombres del Organismo', 'sigefirrhh/base/estructura/NombreOrganismo', 'D', 'sigefirrhh/base/estructura/NombreOrganismo', '1.02.02', 'A');
INSERT INTO public.opcion(id_opcion, codigo_opcion, descripcion, ruta, tipo, uri, jerarquia, estatus) VALUES (690,upper(substr(md5(trunc(random() * 9999999 + 1000000)::text), 1,6)), 'Grupos del Organismo', 'sigefirrhh/base/estructura/GrupoOrganismo', 'D', 'sigefirrhh/base/estructura/GrupoOrganismo', '1.02.03', 'A');
INSERT INTO public.opcion(id_opcion, codigo_opcion, descripcion, ruta, tipo, uri, jerarquia, estatus) VALUES (691,upper(substr(md5(trunc(random() * 9999999 + 1000000)::text), 1,6)), 'Regiones', 'sigefirrhh/base/estructura/Region', 'D', 'sigefirrhh/base/estructura/Region', '1.02.04', 'A');
INSERT INTO public.opcion(id_opcion, codigo_opcion, descripcion, ruta, tipo, uri, jerarquia, estatus) VALUES (692,upper(substr(md5(trunc(random() * 9999999 + 1000000)::text), 1,6)), 'Sedes', '/sigefirrhh/base/estructura/Sede', 'D', '/sigefirrhh/base/estructura/Sede', '1.02.05', 'A');
INSERT INTO public.opcion(id_opcion, codigo_opcion, descripcion, ruta, tipo, uri, jerarquia, estatus) VALUES (693,upper(substr(md5(trunc(random() * 9999999 + 1000000)::text), 1,6)), 'Lugares de Pago por Sedes', 'sigefirrhh/base/estructura/LugarPago', 'D', 'sigefirrhh/base/estructura/LugarPago', '1.02.06', 'A');
INSERT INTO public.opcion(id_opcion, codigo_opcion, descripcion, ruta, tipo, uri, jerarquia, estatus) VALUES (694,upper(substr(md5(trunc(random() * 9999999 + 1000000)::text), 1,6)), 'Unidades Administradores', 'sigefirrhh/base/estructura/UnidadAdministradora', 'D', 'sigefirrhh/base/estructura/UnidadAdministradora', '1.02.07', 'A');
INSERT INTO public.opcion(id_opcion, codigo_opcion, descripcion, ruta, tipo, uri, jerarquia, estatus) VALUES (695,upper(substr(md5(trunc(random() * 9999999 + 1000000)::text), 1,6)), 'Unidades Ejecutoras Locales', 'sigefirrhh/base/estructura/UnidadEjecutora', 'D', 'sigefirrhh/base/estructura/UnidadEjecutora', '1.02.08', 'A');
INSERT INTO public.opcion(id_opcion, codigo_opcion, descripcion, ruta, tipo, uri, jerarquia, estatus) VALUES (696,upper(substr(md5(trunc(random() * 9999999 + 1000000)::text), 1,6)), 'Unidades Ejecutoras por Unidad Administradora', 'sigefirrhh/base/estructura/AdministradoraUel', 'D', 'sigefirrhh/base/estructura/AdministradoraUel', '1.02.09', 'A');
INSERT INTO public.opcion(id_opcion, codigo_opcion, descripcion, ruta, tipo, uri, jerarquia, estatus) VALUES (697,upper(substr(md5(trunc(random() * 9999999 + 1000000)::text), 1,6)), 'Estructuras Organizativas', 'sigefirrhh/base/estructura/Estructura', 'D', 'sigefirrhh/base/estructura/Estructura', '1.02.10', 'A');
INSERT INTO public.opcion(id_opcion, codigo_opcion, descripcion, ruta, tipo, uri, jerarquia, estatus) VALUES (698,upper(substr(md5(trunc(random() * 9999999 + 1000000)::text), 1,6)), 'Unidades Funcionales', 'sigefirrhh/base/estructura/UnidadFuncional', 'D', 'sigefirrhh/base/estructura/UnidadFuncional', '1.02.11', 'A');
INSERT INTO public.opcion(id_opcion, codigo_opcion, descripcion, ruta, tipo, uri, jerarquia, estatus) VALUES (699,upper(substr(md5(trunc(random() * 9999999 + 1000000)::text), 1,6)), 'Tipos de Dependencias', 'sigefirrhh/base/estructura/TipoDependencia', 'D', 'sigefirrhh/base/estructura/TipoDependencia', '1.02.12', 'A');
INSERT INTO public.opcion(id_opcion, codigo_opcion, descripcion, ruta, tipo, uri, jerarquia, estatus) VALUES (700,upper(substr(md5(trunc(random() * 9999999 + 1000000)::text), 1,6)), 'Dependencias Administrativas', 'sigefirrhh/base/estructura/Dependencia', 'D', 'sigefirrhh/base/estructura/Dependencia', '1.02.13', 'A');
INSERT INTO public.opcion(id_opcion, codigo_opcion, descripcion, ruta, tipo, uri, jerarquia, estatus) VALUES (701,upper(substr(md5(trunc(random() * 9999999 + 1000000)::text), 1,6)), 'Tipos de Características(Familias)', 'sigefirrhh/base/estructura/TipoCaracteristica', 'D', 'sigefirrhh/base/estructura/TipoCaracteristica', '1.02.14', 'A');
INSERT INTO public.opcion(id_opcion, codigo_opcion, descripcion, ruta, tipo, uri, jerarquia, estatus) VALUES (702,upper(substr(md5(trunc(random() * 9999999 + 1000000)::text), 1,6)), 'Características de Dependencias', 'sigefirrhh/base/estructura/CaracteristicaDependencia', 'D', 'sigefirrhh/base/estructura/CaracteristicaDependencia', '1.02.15', 'A');
INSERT INTO public.opcion(id_opcion, codigo_opcion, descripcion, ruta, tipo, uri, jerarquia, estatus) VALUES (703,upper(substr(md5(trunc(random() * 9999999 + 1000000)::text), 1,6)), 'Clasificación de Dependencias', 'sigefirrhh/base/estructura/ClasificacionDependencia', 'D', 'sigefirrhh/base/estructura/ClasificacionDependencia', '1.02.16', 'A');
INSERT INTO public.opcion(id_opcion, codigo_opcion, descripcion, ruta, tipo, uri, jerarquia, estatus) VALUES (704,upper(substr(md5(trunc(random() * 9999999 + 1000000)::text), 1,6)), 'Reportes de Estructura', 'sigefirrhh/base/estructura/ReportEstructura', 'D', 'sigefirrhh/base/estructura/ReportEstructura', '1.02.17', 'A');
INSERT INTO public.opcion(id_opcion, codigo_opcion, descripcion, ruta, tipo, uri, jerarquia, estatus) VALUES (705,upper(substr(md5(trunc(random() * 9999999 + 1000000)::text), 1,6)), 'Clases de Cargos y Tabuladores', 'N/A', 'D', 'N/A', '1.03', 'A');



INSERT INTO public.rolopcion(id_rol_opcion, id_rol, id_opcion, consultar, agregar, modificar, eliminar, ejecutar) VALUES (102, '41'::integer, 678, 'S'::text, 'S'::text, 'S'::text, 'S'::text, 'S'::text);
INSERT INTO public.rolopcion(id_rol_opcion, id_rol, id_opcion, consultar, agregar, modificar, eliminar, ejecutar) VALUES (103, '41'::integer, 679, 'S'::text, 'S'::text, 'S'::text, 'S'::text, 'S'::text);
INSERT INTO public.rolopcion(id_rol_opcion, id_rol, id_opcion, consultar, agregar, modificar, eliminar, ejecutar) VALUES (104, '41'::integer, 680, 'S'::text, 'S'::text, 'S'::text, 'S'::text, 'S'::text);
INSERT INTO public.rolopcion(id_rol_opcion, id_rol, id_opcion, consultar, agregar, modificar, eliminar, ejecutar) VALUES (105, '41'::integer, 681, 'S'::text, 'S'::text, 'S'::text, 'S'::text, 'S'::text);
INSERT INTO public.rolopcion(id_rol_opcion, id_rol, id_opcion, consultar, agregar, modificar, eliminar, ejecutar) VALUES (106, '41'::integer, 682, 'S'::text, 'S'::text, 'S'::text, 'S'::text, 'S'::text);
INSERT INTO public.rolopcion(id_rol_opcion, id_rol, id_opcion, consultar, agregar, modificar, eliminar, ejecutar) VALUES (107, '41'::integer, 683, 'S'::text, 'S'::text, 'S'::text, 'S'::text, 'S'::text);
INSERT INTO public.rolopcion(id_rol_opcion, id_rol, id_opcion, consultar, agregar, modificar, eliminar, ejecutar) VALUES (108, '41'::integer, 684, 'S'::text, 'S'::text, 'S'::text, 'S'::text, 'S'::text);
INSERT INTO public.rolopcion(id_rol_opcion, id_rol, id_opcion, consultar, agregar, modificar, eliminar, ejecutar) VALUES (109, '41'::integer, 685, 'S'::text, 'S'::text, 'S'::text, 'S'::text, 'S'::text);
INSERT INTO public.rolopcion(id_rol_opcion, id_rol, id_opcion, consultar, agregar, modificar, eliminar, ejecutar) VALUES (110, '41'::integer, 686, 'S'::text, 'S'::text, 'S'::text, 'S'::text, 'S'::text);
INSERT INTO public.rolopcion(id_rol_opcion, id_rol, id_opcion, consultar, agregar, modificar, eliminar, ejecutar) VALUES (111, '41'::integer, 687, 'S'::text, 'S'::text, 'S'::text, 'S'::text, 'S'::text);
INSERT INTO public.rolopcion(id_rol_opcion, id_rol, id_opcion, consultar, agregar, modificar, eliminar, ejecutar) VALUES (112, '41'::integer, 688, 'S'::text, 'S'::text, 'S'::text, 'S'::text, 'S'::text);
INSERT INTO public.rolopcion(id_rol_opcion, id_rol, id_opcion, consultar, agregar, modificar, eliminar, ejecutar) VALUES (113, '41'::integer, 689, 'S'::text, 'S'::text, 'S'::text, 'S'::text, 'S'::text);
INSERT INTO public.rolopcion(id_rol_opcion, id_rol, id_opcion, consultar, agregar, modificar, eliminar, ejecutar) VALUES (114, '41'::integer, 690, 'S'::text, 'S'::text, 'S'::text, 'S'::text, 'S'::text);
INSERT INTO public.rolopcion(id_rol_opcion, id_rol, id_opcion, consultar, agregar, modificar, eliminar, ejecutar) VALUES (115, '41'::integer, 691, 'S'::text, 'S'::text, 'S'::text, 'S'::text, 'S'::text);
INSERT INTO public.rolopcion(id_rol_opcion, id_rol, id_opcion, consultar, agregar, modificar, eliminar, ejecutar) VALUES (116, '41'::integer, 692, 'S'::text, 'S'::text, 'S'::text, 'S'::text, 'S'::text);
INSERT INTO public.rolopcion(id_rol_opcion, id_rol, id_opcion, consultar, agregar, modificar, eliminar, ejecutar) VALUES (117, '41'::integer, 693, 'S'::text, 'S'::text, 'S'::text, 'S'::text, 'S'::text);
INSERT INTO public.rolopcion(id_rol_opcion, id_rol, id_opcion, consultar, agregar, modificar, eliminar, ejecutar) VALUES (118, '41'::integer, 694, 'S'::text, 'S'::text, 'S'::text, 'S'::text, 'S'::text);
INSERT INTO public.rolopcion(id_rol_opcion, id_rol, id_opcion, consultar, agregar, modificar, eliminar, ejecutar) VALUES (119, '41'::integer, 695, 'S'::text, 'S'::text, 'S'::text, 'S'::text, 'S'::text);
INSERT INTO public.rolopcion(id_rol_opcion, id_rol, id_opcion, consultar, agregar, modificar, eliminar, ejecutar) VALUES (120, '41'::integer, 696, 'S'::text, 'S'::text, 'S'::text, 'S'::text, 'S'::text);
INSERT INTO public.rolopcion(id_rol_opcion, id_rol, id_opcion, consultar, agregar, modificar, eliminar, ejecutar) VALUES (121, '41'::integer, 697, 'S'::text, 'S'::text, 'S'::text, 'S'::text, 'S'::text);
INSERT INTO public.rolopcion(id_rol_opcion, id_rol, id_opcion, consultar, agregar, modificar, eliminar, ejecutar) VALUES (122, '41'::integer, 698, 'S'::text, 'S'::text, 'S'::text, 'S'::text, 'S'::text);
INSERT INTO public.rolopcion(id_rol_opcion, id_rol, id_opcion, consultar, agregar, modificar, eliminar, ejecutar) VALUES (123, '41'::integer, 699, 'S'::text, 'S'::text, 'S'::text, 'S'::text, 'S'::text);
INSERT INTO public.rolopcion(id_rol_opcion, id_rol, id_opcion, consultar, agregar, modificar, eliminar, ejecutar) VALUES (124, '41'::integer, 700, 'S'::text, 'S'::text, 'S'::text, 'S'::text, 'S'::text);
INSERT INTO public.rolopcion(id_rol_opcion, id_rol, id_opcion, consultar, agregar, modificar, eliminar, ejecutar) VALUES (125, '41'::integer, 701, 'S'::text, 'S'::text, 'S'::text, 'S'::text, 'S'::text);
INSERT INTO public.rolopcion(id_rol_opcion, id_rol, id_opcion, consultar, agregar, modificar, eliminar, ejecutar) VALUES (126, '41'::integer, 702, 'S'::text, 'S'::text, 'S'::text, 'S'::text, 'S'::text);
INSERT INTO public.rolopcion(id_rol_opcion, id_rol, id_opcion, consultar, agregar, modificar, eliminar, ejecutar) VALUES (127, '41'::integer, 703, 'S'::text, 'S'::text, 'S'::text, 'S'::text, 'S'::text);
INSERT INTO public.rolopcion(id_rol_opcion, id_rol, id_opcion, consultar, agregar, modificar, eliminar, ejecutar) VALUES (128, '41'::integer, 704, 'S'::text, 'S'::text, 'S'::text, 'S'::text, 'S'::text);
INSERT INTO public.rolopcion(id_rol_opcion, id_rol, id_opcion, consultar, agregar, modificar, eliminar, ejecutar) VALUES (129, '41'::integer, 705, 'S'::text, 'S'::text, 'S'::text, 'S'::text, 'S'::text);

SELECT  id_rol_opcion, rolopcion.id_rol, rolopcion.id_opcion, consultar, agregar, modificar, eliminar, ejecutar    FROM       rol,       opcion,       rolopcion    WHERE       opcion.id_opcion = rolopcion.id_opcion AND      rolopcion.id_rol = rol.id_rol                    AND     rol.id_rol in (      41     )            AND     uri in (      'web/compromiso_inicial/compromiso_inicial'     )                ORDER BY ruta  
